### ISSUE TITLE
Support/Document Transpilation via API

### ISSUE THREAD

**Issue by miho** [mirkosertic/Bytecoder#126]
Very interesting project. Looks great! I have some questions/enhancement proposals:

- So far, the manual only mentions how to perform the transpilation via maven or alternatively a 
   specialized junit runner for testing. Is there an example on how to use the transpiler's api 
   programmatically, without relying on a build tool, such as maven?
- If that's not the case then it would be great to add/document a clean Java API for performing 
  the transpilation programmatically.

**Comment by mirkosertic** [comment]
Hi Michael,

thank you for noticing this project!

At the moment, there is only the Maven Mojo available. I guess it would be easy to create an executable fat-jar to invoke Bytecoder using CLI. In fact most of the code is already written in https://github.com/mirkosertic/Bytecoder/blob/master/maven/src/main/java/de/mirkosertic/bytecoder/maven/BytecoderMavenMojo.java, we just need to add a fancy CLI to it.

Are you planning to use the CLI for demo purposes or embedded into an alternative build process?

**Comment by miho** [comment]
Hi Mirko,

I only need a Java API + documentation. CLI would be cool too but is less important for me. I just wanted to show it to some people at our university and maybe let some students experiment with it. I'm interested in transpilers because I want to explore different options for adding Web support to the generators of the modeling frameworks we are currently developing ([VMF](https://github.com/miho/VMF) and [VMF-Text](https://github.com/miho/VMF-Text)). The question is: do we need another generator for WASM or can we just rely on existing transpilers?

**Comment by mirkosertic** [comment]
I've added a CLI example with the commit from above. It should show how to use the Bytecoder API to invoke the compiler for JS and WASM output. The [manual](https://github.com/mirkosertic/Bytecoder/blob/master/manual/README.md) should show the basic usage of the Bytecoder to Host Binding API, and there are some working examples available in the integrationtest module for now. Unfortunately there is no more documentation is written form yet, just working code.

**Comment by ccinelli** [comment]
I think one of the biggest opportunity to improve this project and increasing its usage is understanding who its users are going to be. 

Even if you can use it to write frontend code in Java, there are going to be a pretty big chuck of users that are not familiar with the Java ecosystem and are trying to compile Java libraries so they can use them in their Javascript projects. I would not assume that people have Java installed on their machine, know know how to use `maven`, etc.

For this reason, I think the installation and build process should be described in details in a section tin he `README.md`. Ideally there is a one line installation that does everything, including dependencies checks and installation like in https://github.com/nvm-sh/nvm#install--update-script or https://brew.sh/ 

At the moment people do not even know where to start.

Then, I think a step by step example of how to compile an interesting Java library, exposing the methods to JS and use that generated `wasm` module in a HTML + JS is requiredt. Currently the examples do not tell you much about how the author went from the source code to a working example.

**Comment by mirkosertic** [comment]
@ccinelli Thank you for your feedback! Help for impoving the documentation is always welcome! Please feel free to submit a PR if you think something is unclear or missing in the documentation.

**Comment by mirkosertic** [comment]
Documentation and CLI were updated.

Bytecoder  2019-06-13 was uploaded today to Maven Central and will be available soon.

Releasenotes:
https://github.com/mirkosertic/Bytecoder/releases/tag/2019-06-13

**Comment by ccinelli** [comment]
Where is the documentation about that? 
Could you a section in the `README.md` ?

**Comment by mirkosertic** [comment]
It is documented in the user manual. Please checkout https://github.com/mirkosertic/Bytecoder/tree/master/manual

**Comment by ccinelli** [comment]
I think ideally somebody landing on the `README.md` should find on it or just a "click away "how to _install_ and _get started_. 

I still do not see how a user can install and compile a simple java program in WebAssembly.

I was also suggesting that a user that do not know `maven` and potentially does not have the `java SDK` can find great help in a short paragraph like those here:  https://github.com/aws/aws-sdk-java-v2/blob/master/README.md#minimum-requirements 

---
#### Minimum requirements ####

To run the SDK you will need **Java 1.8+**. For more information about the requirements and optimum
settings for the SDK, please see the [Installing a Java Development Environment][docs-java-env]
section of the developer guide.

---

These are some `README.md` examples to get some inspiration:
- https://github.com/apache/dubbo
- https://github.com/aws/aws-sdk-java-v2
- https://github.com/apache/skywalking  and the linked
- https://github.com/apache/skywalking/blob/master/docs/en/guides/How-to-build.md
- https://github.com/prisma/graphcool-framework

**Comment by mirkosertic** [comment]
As suggested, feel free to submit a PR for documentation enhancements.

**Comment by ccinelli** [comment]
A even simpler solution (for the user) is a docker container (see #158). 
BTW, the Docker file will also document exactly how to install `bytecoder` that is what I was suggesting.

**Comment by ccinelli** [comment]
BTW, https://github.com/mirkosertic/Bytecoder/blob/master/manual/README.md is GREAT!
