### ISSUE TITLE
RFE simpler JS interface

### ISSUE THREAD

**Issue by WhiteHexagon** [mirkosertic/Bytecoder#129]
Firstly wow!  Thank you for your efforts here.  I have been experimenting with Go and Wasm, but the generated .wasm file size is much smaller with your solution :)

Do you think it would be possible to include a simplified javascript interface?  I really like that you are mapping lots of stuff to concrete Java classes, but for things that have not yet been mapped, a simpler interface would be useful.  For example Go only exposes this:

https://golang.org/pkg/syscall/js/

But that has allowed me already to experiment with WebGL and WebVR.

https://github.com/WhiteHexagon/go2wasm-vr/blob/master/main.go

I'd like to create a similar demo using Bytecoder if possible, since I think the comparison will really show the power of your approach.

**Comment by mirkosertic** [comment]
Hey, thank you for this feedback!

About JavaScript interop. I'am still not sure how to combine custom JavaScript and the upcoming [Wasm Reference Types](https://github.com/WebAssembly/reference-types/blob/master/proposals/reference-types/Overview.md) proposal. Currently, there are a lot of adapter functions created on JS side to adapt JS and the Wasm sandbox. Reference types should increase performance, but the JS integration might still be needed.
However, the idea behind the current implementation is to provide type safe interfaces from within the Wasm module. Adding custom JS can be implemented by annotations on static native methods, but this might break when reference types are available.
Do you think you can create a demo with the current state of Bytecoder? It would be cool to see another usecase. If not, I'd take a look for a prototypal implementation. But this might break in the future.

**Comment by WhiteHexagon** [comment]
There is also WASI in the pipeline, so potentially more changes.  However I think that it is good that you are currently focusing and targeting a specification that is already implemented in all major browsers.  These new changes might take time to reach such a level of adaptation.  

Also the performance seems good from my small test so far, even running on an old Nexus 5 Android device :)  But I will be interested to port my VR cube example over and see how the performance is there, since for that it must run at 90fps...

You can see from my code that being able to determine the size of the parent element is important. (lines 21-23) And yesterday I discovered for canvas 2D the correct handling of retina displays also requires being able to determine the scale (devicePixelRatio) and also set the scale, but also set the 'style' width and height, on the 'canvas' element.  Anyway, you can from my code my there are a few areas that I wouldn't be able to implement currently.  Unless you mean there is a way to work around that?  I didn't quite understand about annotations...

**Comment by mirkosertic** [comment]
I think you need to create a set of Java interfaces to interact with Tree.js. Creating such interfaces is quite simple. Hey are interfaces extenting the OpaqueReferenceType, as seen in the following example:

https://github.com/mirkosertic/Bytecoder/blob/master/classlib/bytecoder.web/src/main/java/de/mirkosertic/bytecoder/api/web/Window.java

Interface method invocations will become method invocations on the underlying JS object. Unless you annotate the method with `@OpaqueProperty`, in this case the method name is the property name to access, and the Java method invocation will be transpiled to a JS property access.

To see it in action, take a look at the main method in https://github.com/mirkosertic/Bytecoder/blob/master/integrationtest/src/main/java/de/mirkosertic/bytecoder/integrationtest/JBox2DSimulation.java. This is the physics demo with HTML Canvas interaction.

**Comment by WhiteHexagon** [comment]
Wow, it really was simple to extend. I will have to study more how you make this magic work :)  I only added a few commands, just to make sure I was doing it correctly, but it seems to work.  Feel free to close this topic! and Thank you!



```
import de.mirkosertic.bytecoder.api.OpaqueProperty;
import de.mirkosertic.bytecoder.api.web.Element;

public interface Div extends Element {
    @OpaqueProperty
    public abstract int clientWidth();

    @OpaqueProperty
    public abstract int clientHeight();

    @OpaqueProperty
    public abstract void style(String stlye);
}
```

**Comment by mirkosertic** [comment]
I'am always glad to help!
