### ISSUE TITLE
Context2D::getImageData

### ISSUE THREAD

**Issue by WhiteHexagon** [mirkosertic/Bytecoder#142]
https://developer.mozilla.org/en-US/docs/Web/API/ImageData

I am trying to add getImageData to Canvas2D, but seeing an error I don't understand:

error: Type conversion to L1BYTE is not supported

This is my attempt:

```
public interface ExtContext extends CanvasRenderingContext2D {
    ExtImageData getImageData(int x, int y, int w, int h);

    @OpaqueProperty
    public abstract void setFont(String f);

    void fillText(String text, int x, int y);
}
```

```
public interface ExtImageData extends OpaqueReferenceType {
    @OpaqueProperty
    byte[] data();
}
```

The font stuff is working fine, so I feel like I'm on the right track, but maybe there is some extra trick for returned arrays?

**Comment by mirkosertic** [comment]
Passing native arrays from JS side to WASM is not supported yet. But you can always pass in a `de.mirkosertic.bytecoder.api.web.Int8Array`

so your class will become:

```
public interface ExtImageData extends OpaqueReferenceType {
    @OpaqueProperty
    de.mirkosertic.bytecoder.api.web.Int8Array data();
}
```

Arrays are currently only passed by reference into the WASM sandbox, so they are a little bit slow to handle as every element access on WASM side becomes an invocation on JS side. I hope this will be easier to implement once the Reference Types Proposal is implemented.

**Comment by WhiteHexagon** [comment]
Thanks, and good to know about the performance.  I was trying to implement a recursive flood fill, so maybe not the best idea at the moment :)  So instead I just captured the image data using 'toDataURL' and handle that externally.
