### ISSUE TITLE
Supporting org.json library

### ISSUE THREAD

**Issue by arstulke** [mirkosertic/Bytecoder#145]
I started with the implementation of an interop library, which should be language and compiler independent.  For that I tried to use the library "org.json"
```
<dependency>
    <groupId>org.json</groupId>
    <artifactId>json</artifactId>
    <version>RELEASE</version>
</dependency>
```

When compiling my test program I get errors about the missing methods or fields:
```
        Integer.bitCount(1234);
        Integer.numberOfTrailingZeros(1234);
        Long.numberOfLeadingZeros(1234L);
        Math.log(1234.0);
        Arrays.copyOf(new int[]{0, 1, 2, 3}, 1, 2);
        Arrays.fill(new int[]{0, 1, 2, 3}, 1, 2, 5);
        Arrays.fill(new int[]{0, 1, 2, 3}, 5);
        Arrays.binarySearch(new int[]{0, 1, 2, 3}, 5);
        Array.getLength(new Object());
        Array.get(new Object[0], 0);
        Math.floorMod(1, 2);
        System.getProperties();
        System.bootLayer
        Character.forDigit(1, 2);
        Character.charCount(1);
        Character.getType(1);
        Character.isSurrogate('a');
        Character.isLowSurrogate('a');
        Character.isHighSurrogate('a');
        Character.isSupplementaryCodePoint(1);
        Character.isValidCodePoint(1);
        Character.codePointAt("abc", 0);
        Character.toUpperCase(1);
        Character.toLowerCase(1);
        Character.valueOf('a');
        new StringBuffer("");
        new StringBuilder(1);
        new String(new int[] {1}, 0, 1);
        new Reference<>(new Object(), new ReferenceQueue<>()){};

        Reference<Object> ref = new Reference<Object>(new Object(), new ReferenceQueue<Object>()){

            public Object get() {
                return super.queue.poll();
            }

        };
```

Herewith I would like to ask if it is possible to support the library "org.json".
Since I have no idea about these deep Java functionalities I ask you, if you want to support the library, to implement these methods and fields.

**Comment by mirkosertic** [comment]
I will implement the mentioned methods as soon as possible.

However, Bytecoder currently does not support the reflection API. Most of JSON marshalling and unmarshalling is done using reflections, so this JSON library might not work properly, the same with Jackson and others.

If you need a very simple example of working with JSON in Bytecoder, take a look at https://github.com/mirkosertic/GameComposer/blob/master/gameengine-bytecoderrenderer/src/main/java/de/mirkosertic/gameengine/bytecoder/JSONParser.java#L191. Here, JSON is mapped to nested Map instances, which works quite well for me.

**Comment by mirkosertic** [comment]
#147

**Comment by mirkosertic** [comment]
Closed due to no further user feedback.
