### ISSUE TITLE
Is there a way to override or add to provided classes (e.g. TArrays)?

### ISSUE THREAD

**Issue by davidmontemayor** [mirkosertic/Bytecoder#148]
Hello! 

I've successfully been able to create new "bridge" classes (e.g. for `java.lang.ByteBuffer`), but I've reached a point in the project we're transpiling that I need to add methods that are being used from `java.util.Arrays` to `TArrays`. Is there a supported way to do so? I've tried basically recreating the package structure, but my new methods are not getting picked up. Thank you for a great project, by the way!

**Comment by mirkosertic** [comment]
Hey! Thank you for using Bytecoder!

Of course it is possible to extend the JDK wrapper types. Take a look at https://github.com/mirkosertic/Bytecoder/tree/master/classlib/java.base/src/main/java/de/mirkosertic/bytecoder/classlib/java. There you will find the current wrapping classes implementation.

If you want to avoid compiling Bytecoder after you've made changes, you can use the base package name `de.mirkosertic.bytecoder.classlib` inside your own project. If everything works well, it is easy to migrate the change to the bytecoder classlib module.

Please feel free to submit a PR if something is missing. Help is always welcome!

**Comment by mirkosertic** [comment]
Closed due to nu further user feedback.
