### ISSUE TITLE
Parameters and return values between Java and Javascript are not validated and converted

### ISSUE THREAD

**Issue by ccinelli** [mirkosertic/Bytecoder#165]
Strings and arrays are not passed correctly between languages.

The `@Export`  should probably do some validation/conversion for inputs and returns values.

Nice to have: "cast" operator for return value. Maybe it can be an extra parameter in the @Export.

Nice to have: A way to extend `Export` to cast Java objects to custom Javascript  structures.
Java: 
```java
import de.mirkosertic.bytecoder.api.Export;

/**
 * Hello world!
 *
 */
public class App 
{
    public static void main( String[] args )
    {
        System.out.println( "Hello World!" );
    }

    @Export("add")
    public static int add(int a,int b)
    {
        return a + b;
    }


    @Export("concat")
    public static String concat(String a, String b)
    {
        return a + b;
    }

    @Export("concatWithParam")
    public static String [] concatWithParam(String a, String b)
    {
        String [] results = new String[3];

        results[0] = a;
        results[1] = b;
        results[2] = a+b;

        return results;
    }
}
```

HTML:
```html
<html>
      <body>
      <script type="text/javascript" src="bytecoder.js"></script>
         <script type="text/javascript">

            console.log("Init");
            bytecoder.bootstrap();

            document.write("3 + 5 = ");
            document.write(bytecoder.exports.add(3, 5));
            document.write("<br />");


            document.write("3 + 5 = ");
            const sumArray = bytecoder.exports.addWithParam(3, 5);

            // FIXME: It does not work
            document.write(sumArray.join(', '));

            // NOTE: This works but it is not what somebody will expect: document.write(sumArray.data.join(', '));
            document.write("<br />");

            // FIXME: This does not work "Uncaught TypeError: _aObject.iof is not a function"
            document.write('concat("go", "at") = ');
            document.write(bytecoder.exports.concat("go", "at"));
            document.write("<br />");

            // FIXME: This does not work because of the input: "Uncaught TypeError: _aObject.iof is not a function"
            // but the output probably will need to be fixed
            document.write('concatWithParam("go", "at") = ');
            const concatArray = bytecoder.exports.concatWithParam("go", "at");
            document.write(concatArray.join(', '));


            console.log("Done");
        </script>
      </body>
</html>
```

**Comment by ccinelli** [comment]
Related with #81

**Comment by tim-coder** [comment]
I have a much simpler use case, which also fails.

Java:

`

    package bytecodertest;

    import de.mirkosertic.bytecoder.api.Export;

    public class HelloWorld {
    
        public static void main(String[] args) {
            System.out.println("Hello World!");
        }
    
        @Export("hello")
        public static void hello(String msg) {
            System.out.println(msg);
        }
    }
`

HTML:
`
                
    <html>
        <body>
            <script type="text/javascript" src="bytecoder.js"></script>
            <script type="text/javascript">
                console.log("Init");
                bytecoder.bootstrap();
                
                bytecoder.exports.main();
                
                // The statement below generates the error:
                // TypeError: _obj.jlStringtoString is not a function
                //
                bytecoder.exports.hello("world");
                
                console.log("Done");
                
            </script>
        </body>
    </html>

`

Browser console:

`

    [Log] Init 
    [Log] Hello World! 
    [Error] TypeError: local_1_REFERENCE.constructor.jlStringgetName is not a function. (In 'local_1_REFERENCE.constructor.jlStringgetName()', 'local_1_REFERENCE.constructor.jlStringgetName' is undefined)
        (anonymous function) (bytecoder.js:339)
        Global Code (page.html:19)


`

Is there a plan for a fix or a work-around?

BTW, passing arguments into the main() method also fails.

**Comment by mirkosertic** [comment]
This Issue is closed due to no further user feedback. It works as designed by the current Opaque Reference Types API and there are no plans to change the behavior.
