### ISSUE TITLE
Example with Maven

### ISSUE THREAD

**Issue by ccinelli** [mirkosertic/Bytecoder#166]
Currently a new user can figure out how to make it work looking at `/integrationtest/pom.xml` but an example in an `/example` folder would make it easier.

**Comment by mirkosertic** [comment]
The integration tests are meant as an example. Also the user manual states how to use the Maven plugin. Additional information can be gathered from the Maven plugin by using the help goal.

**Comment by objectProgrammer** [comment]
Shouldn't this be closed?

**Comment by mirkosertic** [comment]
Closed due to no further user feedback.
