### ISSUE TITLE
Error linking class sun.security.util.Debug

### ISSUE THREAD

**Issue by supertorpe** [mirkosertic/Bytecoder#180]
I have a java project that registers a security provider:

Security.addProvider (new BouncyCastleProvider ());

Running the bytecoder generates this error:

Error linking class sun.security.util.Debug: Can not find constructor <init> in java / lang / String with signature VOID (L1INTINTINT) in class java.lang.String

BouncyCastleProvider inherits from java.security.Provider which, in turn, uses the class sun.security.util.Debug. This class performs some static initialization that the bytecoder should not be liking.

More info:                                                                                                                                                                              java version "1.8.0_201"                                                                                                                                                                       Java(TM) SE Runtime Environment (build 1.8.0_201-b09)                                                                                                                                          Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

**Comment by supertorpe** [comment]
I figured how to fix it adding this class to the project:

`package de.mirkosertic.bytecoder.classlib.sun.security.util;

import de.mirkosertic.bytecoder.api.SubstitutesInClass;

@SubstitutesInClass(completeReplace = true)
public class TDebug
{
  public static TDebug getInstance(String paramString)
  {
    return null;
  }
  
  public static TDebug getInstance(String paramString1, String paramString2)
  {
    return null;
  }
 
  
  public void println(String paramString)
  {
  }
  
  public void println()
  {
  }
  
  public static void println(String paramString1, String paramString2)
  {
  }
  
}
`
Now I get next error: 

Error linking class java.security.Provider: Error linking class java.util.Locale: Cannot find const ructor  in java/util/concurrent/ConcurrentHashMap with signature VOID(INTFLOATINT) in class java.util.concurrent.ConcurrentHashMap

I will try to make wrapper classes as errors appear.

**Comment by mirkosertic** [comment]
Great you figured it out by yourself, congratulations!

Please note that Locale support is currently very experimental in Bytecoder. Also I haven't tested it with advanced cryptography. I guess we will see some strange numerical issues, as JavaScript currently only support 53bit integers, and no corresponding 64 bit datatypes as we know from Java(Long, Double).

I guess there is some work in the compiler required to make it work propertly.

**Comment by mirkosertic** [comment]
Any progress here? How can I help?

**Comment by supertorpe** [comment]
We finally moved to a Javascript library, so we stopped this line of research. Thank you very much for your concern!
