### ISSUE TITLE
Metaprogramming Support

### ISSUE THREAD

**Issue by norzak** [mirkosertic/Bytecoder#186]
Any plans to support something similar to GWT generators or Teavm Metadata since there is no reflection support in Bytecoder.

**Comment by mirkosertic** [comment]
Well, it all depends on your usecase.

Bytecoder currently does not bring its own metaprogramming framework. But I don't hink its a limitation here, as Metaprogramming can always be done using Annotation Processors, that are not directly bound to a specific compiler technology.

Take a look at https://github.com/mirkosertic/GameComposer. This gameengine needs some kind of reflection support to handle Lua Scripting language integration. I've written an Annotation Processor, that generates code to emulate reflections. This code is not bound to a specific compiler, so it is useable by `TeaVM`, `GWT` and `Bytecoder`.

Take a look at the following class:

```
import de.mirkosertic.gameengine.annotations.ReflectiveField;

public class Force implements Reflectable<ForceClassInformation> {

    private static final ForceClassInformation CIINSTANCE = new ForceClassInformation();

    @ReflectiveField
    public final float forceX;

    @ReflectiveField
    public final float forceY;

    public Force(float aForceX, float aForceY) {
        forceX = aForceX;
        forceY = aForceY;
    }

    @Override
    public ForceClassInformation getClassInformation() {
        return CIINSTANCE;
    }
}
```

`@ReflectiveField` marks a field that will become available by reflection emulation. The Annotation Processor generates the wolloging `ForceClassInformation`. which is used to access fields at runtime:

```
public class ForceClassInformation extends ClassInformation {

  public final Field<Force, Float> FORCEX = new Field<Force, Float>("forceX", Float.class) {
    @Override
    public Float getValue(Force aObject) {
      return aObject.forceX;
    }
  };

  public final Field<Force, Float> FORCEY = new Field<Force, Float>("forceY", Float.class) {
    @Override
    public Float getValue(Force aObject) {
      return aObject.forceY;
    }
  };

  public ForceClassInformation() {
    register(FORCEX);
    register(FORCEY);
  }
}
```

which extends

```
public abstract class ClassInformation {

    private final Map<String, Field> fields;
    private final Map<String, Method> methods;

    protected ClassInformation() {
        fields = new HashMap<String, Field>();
        methods = new HashMap<String, Method>();
    }

    protected void register(Field aField) {
        fields.put(aField.getName(), aField);
    }

    protected void register(Method aMethod) {
        methods.put(aMethod.getName(), aMethod);
    }

    public Field[] getFields() {
        return fields.values().toArray(new Field[fields.size()]);
    }

    public Field getFieldByName(String aFieldName) {
        return fields.get(aFieldName);
    }

    public Method getMethodByName(String aMethodName) {
        return methods.get(aMethodName);
    }

    public Method[] getMethods() {
        return methods.values().toArray(new Method[methods.size()]);
    }
}
```

So at runtime we can do something like

```
fieldValue = Force.CIINSTANCE
                       .fieldByName('forceX')
                       .getValue(someObjectIWantToAccessTheFieldFrom);
```

So, at the moment Bytecoder has no build in Metaprogramming support, but there are many ways to get around this without creating a hard compiler vendor lock-in.

**Comment by norzak** [comment]
Thanks for the pointer, I will check the processor at game composer source tree. I also agree fully on not locking people on a specific implementation, but an example in documentation would always help a lot.

**Comment by mirkosertic** [comment]
Closed due to no further user feedback.
