### ISSUE TITLE
Directly emit WebAssembly binary code

### ISSUE THREAD

**Issue by mirkosertic** [mirkosertic/Bytecoder#19]
This would remove the WABT dependency from the project.

**Comment by gouessej** [comment]
Do you use WABT only to convert the WebAssembly code from text format to binary format?

**Comment by gouessej** [comment]
Maybe you could use [Asmble](https://github.com/cretz/asmble) to convert the text into S-expressions, the S-expressions into an abstract syntax tree and this abstract syntax tree into binary.

**Comment by mirkosertic** [comment]
There are no dummy questions! Thanks for the link to Asmble.

For now, I am searching for an Java AST and a way to render the AST into the WebAssembly binary representation, maybe also with a validator included. Does Asmble provide something linke this?

**Comment by gouessej** [comment]
Yes it does but most of the source code is written in Kotlin:
[convert the text into S-expressions](https://github.com/cretz/asmble/blob/master/compiler/src/main/kotlin/asmble/io/StrToSExpr.kt)
[S-expressions into an abstract syntax tree](https://github.com/cretz/asmble/blob/master/compiler/src/main/kotlin/asmble/io/SExprToAst.kt)
[abstract syntax tree into binary](https://github.com/cretz/asmble/blob/master/compiler/src/main/kotlin/asmble/io/AstToBinary.kt)

**Comment by mirkosertic** [comment]
Duplicate to #62 Will be released soon :-)
