### ISSUE TITLE
There are any plans to support AWT?

### ISSUE THREAD

**Issue by yuripourre** [mirkosertic/Bytecoder#225]
I found this project recently, seems very promising. I dived into documentation but couldn't find anything related to AWT. How do you think would be the best way to produce Canvas (browser) code from AWT code?

**Comment by mirkosertic** [comment]
Well, currently there is no support for AWT or Swing yet. I think it is possible to implement this, but I don't think it is possible to compile any working Swing application into JS with Bytecoder yet, as Bytecoder does not support Java reflections, which are most often used in Swing code.

Using the Swing component tree to render user interfaces should be possible, but the wrapper types have to be implemented.

**Comment by yuripourre** [comment]
Thank you for the answer. I am only interested into porting awt since I have some projects that use it. Seems like it would be slightly easier to port than Swing.

I will keep an eye on this project.
