### ISSUE TITLE
Newline in Strings cause compile to fail

### ISSUE THREAD

**Issue by Karang** [mirkosertic/Bytecoder#23]
Hi,
I just noticed that if you have a newline in a string, for instance : `System.out.println("Hello\nWorld");`, the generated .wat is ill-formed.
One simple fix is to change the line 729 of WASMSSACompilerBackend.java to : `theWriter.println(theData.replaceAll("(?:\\n|\\r)", ""));`
Best regards,
Karang

**Comment by Karang** [comment]
I started to write a WebGL port using your compiler, and managed to run a simple example : https://github.com/Karang/JWebGL/blob/master/src/main/java/fr/karang/jwebgl/Lesson001.java
While looking the code I noticed a few things that could be improved : 
- the strings are stored as array of int instead of bytes taking 4 time more memory : it should be easy to pack them before writing them and could allow to read them in one go in javascript `new TextDecoder("utf-8").decode(new UInt8array(mem.buffer, offset, length))`
- the toLowerCase function of TCharacter could be reduced to `return (char)(aChar-'A'+'a');` + some range checking -> this is faster than a lot of branching
- it could be nice to generates the dynamic linking object with the compiler to remove unused javascript functions (when we'll add webgl1,2 + canvas api 2D, that's a lot of functions), also there might be a way to optionally embed the js code in the methods annotation to regroup the js and java code

I also have a question : is there a way to return a string from a js call ? Does the js function have to create the TString object in memory and pass the reference ? Maybe it would be easier if memory was managed on js side ?

**Comment by mirkosertic** [comment]
Wow, that are great news! I am glad this compiler is helpful to others!

Your questions:
* You are right, primitive array handling can be greatly improved to reduce the memory footprint and make JS interaction easier. I used i32/f32 for primitives and references as this made the design for the first compiler version easier. But this can of course be enhanced. I've created #24 for that.
* Bug fixed and improvements in general: You have very good suggestions, would you mind submitting a PR for that? Contributions are always and very welcome!

At the moment, the only way to interact between JS and WASM is passing primitives like i32/f32 around or by accessing the linear memory. So the only way to create a TString from JS side would be to call factory function to create a new TStringBuilder, call append for every character from JS side and then create a TString from it. But this object would be of temporary nature, as it is not referenced anywhere so it would be GCed if memory gets low.

Also keep in mind that passing the JS/WASM bridge comes with a performance penalty, as there is a lot of object marshaling involved. So using JS for memory management would probably be a slower.

**Comment by mirkosertic** [comment]
Dynamic linking: Well, the JS import object stub could be generated by the compiler for all imported required by the runtime. All user-defined imports must be provided by someone else, so either generated implementation would thow a NotImplementedException or would left out completely. What do you think?
