### ISSUE TITLE
Improve primitive array handling to further reduce memory footprint

### ISSUE THREAD

**Issue by mirkosertic** [mirkosertic/Bytecoder#24]

**Comment by Karang** [comment]
The char type in java is 2 bytes wide but the internal representation of a String object could be less than 2*size bytes, depending on the encoding.
For instance, if using UTF-8 encoding, all most common ascii character are 1 byte wide but other characters are 2 bytes wide.
We can compute the memory footprint of a string like this `"some string with special char : é".getBytes("UTF-8").length`. We'll have to store the real size in bytes and the string length as they could be different values. But then the implementation of set/getCharAt is a bit more tricky. To test if a char is in two part, in UTF-8, the first byte should be >0x80.
A medium improvement would be to use 2 bytes (shorts) for all characters.
