### ISSUE TITLE
String is missing critical APIs

### ISSUE THREAD

**Issue by objectProgrammer** [mirkosertic/Bytecoder#249]
Bytecoder 2019-08-30. Using String::toUpperCase caused the runtime error "unreachable executed" in Firefox and "unreachable" in Chromium which doesn't tell a lot so it took some time to figure out the cause.

- [ ] String::split
- [ ] String::replaceAll
- [ ] String::toLowerCase
- [ ] String::toUpperCase
- [ ] String.join
- [ ] String.valueOf(byte)

Also, unrelated but is it possible to extend existing T-classes such as TString? I haven't really figured out how the @SubstitutesInClass works.

What is the variable name style of this project? Is it `aVariable` or `variable` or `theVariable`? I've seen all and I'm not sure which one is preferred.

**Comment by mirkosertic** [comment]
String/CharSequence implementation is indeed very incomplete. I am currently working on #234 which which remove the TString shadow emulation type and rely on the OpenJDK implementation.

**Comment by mirkosertic** [comment]
The fix was merged with #248 into master and will become available with the next release.
