### ISSUE TITLE
Create better documentation

### ISSUE THREAD

**Issue by mirkosertic** [mirkosertic/Bytecoder#252]

**Comment by objectProgrammer** [comment]
Hello, some time ago I wrote a small wiki for getting started with Bytecoder. I published it a few minutes ago at https://github.com/objectProgrammer/BytecoderWiki but I need help with [issue #1](https://github.com/objectProgrammer/BytecoderWiki/issues/1). Maybe we can merge it with the new documentation you're making?

**Comment by mirkosertic** [comment]
@objectProgrammer it would be really cool to merge the content into the new documentation. I currently have a working version based on markdown content and Hugo as a static site generator. The markdown files will be part of the Bytecoder git repository and are automatically build after a commit to the master branch. So yes, we will definitely merge it!

The release of the new documentation is planned for next week, so after that we can merge your content. I also have some comments about issue 1. Here is the documentation text:

```
`java.lang.String` references are a special case. They are objects in the sence of the JVM,
but they are not automatically converted to JavaScript String instances on host side due to
the expensive conversion operation and its potential performance impact. However, there are
handy conversion operations available to do it if its really needed.
The conversion functions are part of the global `bytecoder` object as 
`bytecoder.toJSString(aBytecoderString)` and `bytecoder.toBytecoderString(aJSString)` respectively.
```

So if you need a JavaScript string, call bytecoder.toJSString, and if you want to return a JavaScript string to bytecoder, convert it by calling bytecoder.toBytecoderString

**Comment by objectProgrammer** [comment]
Not sure where the best place to put this is but I think you linked the wrong page in the README section User Manual.

**Comment by mirkosertic** [comment]
Travis CI build was not complete :-)
The new documentation is now available here: https://mirkosertic.github.io/Bytecoder

**Comment by mirkosertic** [comment]
The new documentation is up and running. @objectProgrammer would you like to file a pr with your documentation enhancements or shall I adapt some content from your Wiki?

**Comment by objectProgrammer** [comment]
You're free to take anything from my wiki (note: I didn't solve issue 1 yet, don't forget to apply your solution to the examples in that issue). I have no experience from markdown wikis and would probably do it incorrectly.

**Comment by mirkosertic** [comment]
@objectProgrammer I've added your content as requested to the documentation. It is avaiable here:
https://mirkosertic.github.io/Bytecoder/chapter-1/page-1-g/

The latest build is still running. You should see the final version in 1-2 hours online. Feel free to use the upper left button "Edit this page", which will lead you to the markdown sources in the GitHub repository if you like to make additional changes. Each change will create a PR.

This issue is closed for now.
