### ISSUE TITLE
Publish Snapshots and Releases using JitPack

### ISSUE THREAD

**Issue by mirkosertic** [mirkosertic/Bytecoder#254]

**Comment by objectProgrammer** [comment]
Hello, I think you've got the wrong idea about JitPack. The service works by adding the JitPack repository to your pom.xml/build.gradle and then you add a dependency such as com.github.mirkosertic.bytecoder:bytecoder-core:master-SNAPSHOT (master-SNAPSHOT can be replaced with commit hash or release tag). JitPack will automatically compile it (first time takes a while and usually produces timeout errors) and you'll be able to use the latest snapshot without having to build or publish anything by yourself. However, when I tried to use the maven plugin with JitPack I got errors about package mismatch.

**Comment by mirkosertic** [comment]
@objectProgrammer this is also my understanding of Jitpack. However, I prefer Maven central for software releases as it is a trusted source and all artifacts are PGP signed. The purpose of this ticket is to give JitPack a try.

**Comment by objectProgrammer** [comment]
Oh okay, the word publish in the title confused me.

**Comment by mirkosertic** [comment]
It is indeed a little bit confusing title ;-)

**Comment by mirkosertic** [comment]
JitPack seems to change the maven coordinates in terms of groupId and artifactId. This is not a viable solution. This ticket is closed.
