### ISSUE TITLE
Limit Wasm GC intervals

### ISSUE THREAD

**Issue by mirkosertic** [mirkosertic/Bytecoder#285]
A single GC run currently crawls all the allocated memory blocks and tries to free them. This process takes a very long time. Goal is to limit the number of allocated memory blocks of a single GC run, and make the GC restartable. This allows to run the GC more often, and will reduce the stop-the-world time per single GC run.

**Comment by mirkosertic** [comment]
@objectProgrammer branch #285 includes the new incremental garbage collector. See the indexwasm.html files (part of integrationtest module) about how to activate it. This should fix the mentioned performance problems, as the GC is incremental and generational.

**Comment by mirkosertic** [comment]
Merged to master

**Comment by objectProgrammer** [comment]
`RuntimeError: indirect call signature mismatch`
`RuntimeError: unreachable executed`

Mouse/keyboard events stop working after like 1 second, the program crashes after a while (out of memory)

**Comment by mirkosertic** [comment]
Hmm, do you have a testcase for this? One limitation of the current model are eventlisteners for opaque reference types. The GC does not treat them as strongly referenced, so we have to create a strong reference by hand, see the Vue example in integrationtests.

**Comment by mirkosertic** [comment]
I've pushed a new commit to master. OpaqueReference callbacks are not not GCed.

**Comment by objectProgrammer** [comment]
Events work now but there is still a memory leak. However, I've lost interest in this project and will abandon my projects. I might update BytecoderGradle from time to time but if you want ownership transferred then we can discuss it. Thanks for your time.
