### ISSUE TITLE
OpaqueTypes error

### ISSUE THREAD

**Issue by objectProgrammer** [mirkosertic/Bytecoder#290]
There seems to be some confusion here, either multiple OpaqueTypes with method named "methodName" or mix of Opaque and Non-Opaque virtual invocations in class list [...]

The only solution I've found is to rename the method to something else, as I don't really know why this is happening.

While the class is indeed extending a class which implements OpaqueReferenceType, the method itself is not an OpaqueMethod.

**Comment by mirkosertic** [comment]
Merged to master
