### ISSUE TITLE
Emulating classes and methods for external libraries

### ISSUE THREAD

**Issue by blackbirdone** [mirkosertic/Bytecoder#293]
Hello :)

I have a question about your project.

I don't really know how to use the Emulating classes and methods part of your documentation.
Is that example "de.mirkosertic.bytecoder.classlib" only usable from your main repository? So i have to add new classes for JRE Emulation to a checkout of you repository and compile it myself or is it possible to include that to my main project, without touching your code base? And if so how?

Also can that be used to overwrite ANY class in ANY library?
As an example:

my.funny.library_1.BadClass
my.otherfunny.library_1.SecondBadClass

Can i overwrite any of this classes with shadow types? That would be really helpful.

my.project.main.java.classlib.my.funny.library_1.TBadClass
my.project.main.java.classlib.my.otherfunny.library_1.TSecondBadClass

kind regards

**Comment by objectProgrammer** [comment]
You need to use `de.mirkosertic.bytecoder.classlib`, for example create a class called `de.mirkosertic.bytecoder.classlib.java.lang.Something` and annotate it with @SubstitutesInClass

**Comment by objectProgrammer** [comment]
I don't know about external libraries but it would probably be `de.mirkosertic.bytecoder.classlib.my.funny.library_1.TBadClass`.

**Comment by mirkosertic** [comment]
The shadow type facility is currently only used to monkey patch the JDK classlib to rewrite parts for Bytecoder compatibility / support. However, it can be used to patch all classes that are part of the classpath as long as you prefix the package name with `de.mirkosertic.bytecoder.classlib`.

There is some documentation available at https://mirkosertic.github.io/Bytecoder/chapter-1/page-1-g/ explaining the basics. However, patching existing libraries is very tricky, so maybe you want to do some preprocessing with tools like https://github.com/raphw/byte-buddy.

**Comment by blackbirdone** [comment]
The problem with that is its not working at all. I think i do something wrong.

The basic structure for an example:

```
+-- classes
    +-- src
        +-- main
            +-- java
                +-- website
                    +-- Controller.class
                +-- de
                    +-- mirkosertic
                        +-- bytecoder
                            +-- classlib
                                +-- website
                                    TController.class
```        
TController is annotated with @SubstitutesInClass

and contains a method 

```
 public void helloWorld(){
    System.out.println("TEST B");
  }
```

The Controller class contains the Method aswell

```
public void helloWorld(){
    System.out.println("TEST A");
  }
```

`java -jar bytecoder-cli-2019-11-25-executable.jar -classpath=./build/classes/java/main -mainclass=website.Main -builddirectory=./bytecoderOut -backend=js -minify=false`

I don't know why, but i'm not able to replace the class for this easy example.

**Comment by mirkosertic** [comment]
I'll investigate. By the way, could you elaborate your usecase to help me unterstanding the problem better?

**Comment by blackbirdone** [comment]
Hello sorry for the delay, i was busy these days.

I provide you a basic repository with a test that i build for you, maybe it is better so investigate if a do some mistakes or understand something wrong. (maybe just the path is incorrect...)

https://github.com/blackbirdone/bytecoder-test 
and the lib is really just a single class for testing
https://github.com/blackbirdone/test-lib.

The bytecode is provided as well, so you can just run it in minutes if you like. Would be really helpful.

So the main purpose is to just evaluate some transpiler frameworks to decide if it is viable to use java as the main language without writing all javascript code from scratch for a new java client.
So the goal is to rebuild some stuff and keep in mind that a webclient would be really helpful.

There are not that many frameworks at all and your project (or yours?) seems really nice to dig a little bit deeper how decompiling works, with the new webassambly standard which is finilized today it is even more possible to direct execute code in the browser, and just build the ui.

But there are library's that are already existing in the codebase as an e.x. some with vertex abstraction. but there are plain javascript vertex implementations so with the feature to change them on the transpiling step, i can decide if i just use the "real" implementation instead of the transpiled one, and i doesn't need to change anything on the library itself.

I see that it works with the jdk

thank you for you help

**Comment by mirkosertic** [comment]
Thanks for the test case, I will investigate it.

Bytecoder itself has no deep frontend framework integration built in. However, the opaque type system allows to build a transparent API to one. An example with vue.js integration is available.

I don't think it would be useful to implement a complete UI framework in Java and use it with Bytecoder, as there are many good options available in the frontend-world. It really depends on the usecase.

Maybe it is possible to use Java Swing or even JavaFX and compile that to JS / WebAssembly. Problems here arise with acessibility standards. Most cross-compilers I know use the Browser as a kind of framebuffer, and render the Swing / FX UI either pixel by pixel or generate some interactive SVG, making it hard to integrate with screen readers, touch devices etc.

I've used Bytecoder to fully transpile a Java GameEngine to JavaScript and WebAssembly. The project can be seen here: https://github.com/mirkosertic/GameComposer and pushed the limits very far by running the app in Electron or with Polymer as a UI toolkit. But to make this possible the code base must be ready for it. Transpiling some legacy applets or creating a WebStart replacement is a different story ;-)

**Comment by mirkosertic** [comment]
Closed due to no further user feedback.

**Comment by keesvandieren** [comment]
@mirkosertic  / @blackbirdone not sure if still relevant to you. 

We had the same problem. We now have solved it in a simple way.

Repository: https://github.com/squins/libgdx-wasm-with-bytecoder/tree/classlib-gdx-in-bytecoder

Scenario: a third-party library has a class BufferUtils with native (JNI) code in it. For Bytecoder we want to replace it with our own class.

Steps:
1. gdx-backend-bytecoder-shaded produces a shaded jar. In the Maven shader plugin, we add classes to exclude. This module also has (in src/main/kotlin) the replacement classes, e.g. our own version of BufferUtils without native code
2. gdx-backend-bytecoder-example module has a dependency on gdx-backend-bytecoder-shaded, and has the bytecoder maven plugin. This now uses the shaded, correct jar as source.

The disadvantage is that each class to be replaced needs to be explicitly specified in the shaded pom.xml maven module, but at least you have complete control and it works s expected.
