### ISSUE TITLE
exceptions are thrown on init invocation on prototypes

### ISSUE THREAD

**Issue by blackbirdone** [mirkosertic/Bytecoder#304]
Hello
i provided a test here https://github.com/blackbirdone/bytecoder-test/tree/master/example

there is an issue with exceptions

 private void init() {
    try {
      createElement();
      System.out.println("exception not raised");
    }catch (NullPointerException npe){
      System.out.println("exception catched");
    }
  }

  private void createElement() throws NullPointerException {
    throw new NullPointerException();
  }

the javascript code 

C.prototype.VOIDcreateElement = function() {
        var r0 = null;
        $S_0 : {
            r0 = jlNullPointerException.VOID$newInstance();
        }
        throw {exception :r0, stack : new Error().stack};
    };

raises instantly an exception on invoking bytecoder.bootstrap();

**Comment by mirkosertic** [comment]
Hmm, did you enable exception handling for the compiler? By default, it is turned off and no exception handler code is generated, resulting in the described behavior.

Details about the configuration are written here: https://mirkosertic.github.io/Bytecoder/chapter-1/page-1-b/

However, please note exception handling is only supported for the JS backend, as the Wasm exception handling proposal is currently only a working draft.

**Comment by blackbirdone** [comment]
Ohhhhhhh okay... the description is a  little bit short for that. I thought that it had something to do with the transpiler itself and nothing with the output :)

Okay than this was my fault, it worked for all the testcases after enabling it. Works like a charm now :D

Maybe it is something that should be turned on by default? Or we can add something more to the description if you like?

**Comment by mirkosertic** [comment]
Contributions are always welcome! Feel free to edit the manual by clicking the "Edit this page" link on the top-right of the page. This allows you to edit the markdown file and create a PR from your changes!

**Comment by mirkosertic** [comment]
Closed due to no further feedback.
