### ISSUE TITLE
default method on interfaces cannot be overwritten

### ISSUE THREAD

**Issue by blackbirdone** [mirkosertic/Bytecoder#325]
While validating more code an error occur.

The reason is that a interface with a method like that.

```
interface InterfaceA{

  default test(){
    System.out.println("InterfaceA")
  }
}
```
cannot be overwritten by a class

```
class ClassA implement InterfaceA{

  public test(){
    System.out.println("ClassA ")
  }
}
```
it prints always "InterfaceA" if you transpile ClassA

**Comment by mirkosertic** [comment]
Can you please test the setup with all optimizations disabled, passing 'NONE' as the optimizer settings? Maybe the virtual methid call optimizer is running amok in this case.

**Comment by mirkosertic** [comment]
Seems to be an issue with the optimizer.

**Comment by mirkosertic** [comment]
Fix merged to master
