### ISSUE TITLE
JS: generic object cast breaks the script

### ISSUE THREAD

**Issue by blackbirdone** [mirkosertic/Bytecoder#326]
Not a really big issue, but a bug anyway.

If you use a function like that

```
public static <T> T cast(Object x) {
    return (T) x;
}
```

the javascriptcode breaks completely because all methods after that on that casted object cannot be invoked.

**Comment by mirkosertic** [comment]
Hmm, interesting. Can you please specify how it breaks and give examples?

The following unit test is working:

```
@RunWith(BytecoderUnitTestRunner.class)
public class StringTest {

    public static String getString() {
        return "123";
    }

    public static <T> T cast(Object x) {
        return (T) x;
    }

    @Test
    public void testLength() {
        final String theTest = cast(getString());
        Assert.assertEquals(3, theTest.length(), 0);
    }
}
```

**Comment by mirkosertic** [comment]
Closed due to no further feedback. I've added the testcase to the project to make sure there are no regressions in further releases for this topic.
