### ISSUE TITLE
JS: constructor as reference produce an error

### ISSUE THREAD

**Issue by blackbirdone** [mirkosertic/Bytecoder#328]
```
public class TestConstructorInvoke<T> {

  public static void main(String[] args) {
    TestConstructorInvoke<TestObject> testConstructorInvoke = new TestConstructorInvoke<>();
    testConstructorInvoke.test(TestObject::new);
  }

  TestConstructorInvoke() {

  }
  
  public void test(Supplier<T> layoutSupplier) {
    T t = layoutSupplier.get();
    System.out.println(t.toString());
  }

  public static class TestObject {

    @Override
    public String toString() {
      return "TestConstructorInvoke{}";
    }
  }
}
```

The programm crashes because of the constructor reference.

if you change line: 4  from
` testConstructorInvoke.test(TestObject::new);`
to
`testConstructorInvoke.test(() -> new TestObject());`
it works like expected

I think its not a Problem from the supplier but the reference because it breaks on other methods to.
`Function<T, T> layoutSupplier` produces the same result

**Comment by mirkosertic** [comment]
Fix merged to master
