### ISSUE TITLE
Kotlin to WASM 'unreachable executed'

### ISSUE THREAD

**Issue by WhiteHexagon** [mirkosertic/Bytecoder#330]
I finally got some time to try again to get my Kotlin working  :)  I listed my previous progress against the 'gradle plugin' topic, but now I try to get further... So  I have stripped down my code to the bare minimum now.

With this Java it works fine:

```
package art;

public class EntryJava {
    public EntryJava() {
        new Main();
    }

    public static void main(String[] args) {
        new EntryJava();
    }
}
```

With this Kotlin I get an error:

```
package art

class EntryKotlin {
    init {
        println("new entry")
        Main()
    }

    companion object {
        @JvmStatic
        fun main(args: Array<String>) {
            EntryKotlin()
        }
    }
}
```

Main.kt is Kotlin:
```
package art

import de.mirkosertic.bytecoder.api.web.Window

class Main {
    init{
        println("main init")
    }
    private var window: Window? = null
}
```

I am using shadowJar to build my .jar, and then this command line:
`
java -jar bytecoder-cli-2019-06-13-executable.jar -classpath=./build/libs/art-trimmed-all.jar -mainclass=art.EntryKotlin -builddirectory=build -backend=wasm -minify=false -optimizationlevel=ALL -filenameprefix=main -maximumwasmpages=1024`

Running with Firefox 60 give this error:
`RuntimeError: unreachable executed`

I also tried with main as a top level function, and changing the above to art.EntryKotlinKt, but same results.  Same error if I specify art.EntryKotlin$CompanionObject on the above command line. [Edit] I am assuming it is something to do with finding the main method, since that seems to be the only difference between my two entry implementations...

Also I should mention I am on macos 10.12.4 running this version of java:

```
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
```

**Comment by mirkosertic** [comment]
You are hitting Kotlins null-check intrintics when calling the main method from JS-Side. I guess you pare passing 0 here, right? 0 == Null-Reference.
Try using the delaration `fun main(args: Array<String>?)` which makes the args reference nullable.

**Comment by WhiteHexagon** [comment]
Awesome, good catch, that was indeed the error.  I never even considered that the error could be coming from that side.  I just cut and pasted the html&js and haven't touched it since, trying to do as much from WASM as possible :)    Thanks!  I never would have solved that one.


```
<body id="body">
    <script>
        var instantiated = function (result) {
            bytecoder.init(result.instance);
            bytecoder.exports.initMemory(0);
            bytecoder.exports.bootstrap(0);
            bytecoder.exports.main(0);
        };
        WebAssembly.instantiateStreaming(fetch('main.wasm'), bytecoder.imports).then(instantiated);
    </script>
    <div id="app" />
</body>
```
