### ISSUE TITLE
RFE specify name of wasmbindings.js

### ISSUE THREAD

**Issue by WhiteHexagon** [mirkosertic/Bytecoder#351]
Is there currently any way to specify the name of this generated file?  

I found the cli option:

`-filenameprefix=main`

but that results in:

```
main_wasmbindings.js
main.wasm
```

Ideally I would like to have:

```
main.js
main.wasm
```

**Comment by mirkosertic** [comment]
The name is currently hardcoded. We have to change the software to make it configurable.

**Comment by mirkosertic** [comment]
Merged to master

**Comment by WhiteHexagon** [comment]
great! thank you :)
