### ISSUE TITLE
Failed to compine java.util.Locale with maven plugin

### ISSUE THREAD

**Issue by Cleiton-D** [mirkosertic/Bytecoder#354]
I'm using the maven plugin and I'm getting this error about java.util.Locale

` Error running bytecoder: Cannot find virtual method getUnicodeLocaleType in non-abstract class java/util/Locale with signature java.lang.String(java.lang.String)`

**Comment by JFronny** [comment]
How did you fix this? I am currently experiencing what seems to be the same issue.
