### ISSUE TITLE
Documentation: How to use the LLVM backend for WASM

### ISSUE THREAD

**Issue by WhiteHexagon** [mirkosertic/Bytecoder#357]
I have some basic stuff running with cli June'19, but having some issues making progress now.  So I have decided to try the new LLVM backend you are working on, great idea!  thanks.

I have downloaded LLVM 10.0.0 for macos from:  `https://llvm.org/`
Info for others:

```
gunzip clang+llvm-10.0.0-x86_64-apple-darwin.tar.xz
tar -xf clang+llvm-10.0.0-x86_64-apple-darwin.tar 
```

However, looking in the `bin` directory, I don't see the two commands you referenced in your documentation: `lld-10` and `wasm-ld-10`

There are commands `lld` and `wasm-ld`, but the later is only a symlnk `wasm-ld -> lld`

Did I get the wrong version, or do something wrong?

**Comment by mirkosertic** [comment]
It all depends which distribution was used to install LLVM.

In case of downloading the .tar.gz, you have to create the symlinks `llc-10` -> `llc`and `wasm-ld`-> `wasm-ld' by hand. Other distributions create them for you in case you have multiple LLVM installations on the same machine.

**Comment by WhiteHexagon** [comment]
Thanks!  So I switched back now to the Feb'20 cli build and tried the new backend, but I am still seeing the exception I mentioned on the other issue :(

[https://github.com/mirkosertic/Bytecoder/issues/333](issue 333)

`Caused by: java.lang.RuntimeException: Error linking class sun.nio.cs.UTF_8`

This is still using Kotlin, which works with June'19 cli build:

`Kotlin version 1.3.21-release-158 (JRE 1.8.0_161-b12)`

**Comment by mirkosertic** [comment]
Closed as answered.
