### ISSUE TITLE
Annotation Support?

### ISSUE THREAD

**Issue by norzak** [mirkosertic/Bytecoder#370]
Any plans to support Annotations? 

Methods missing in Class needed for minimal support;
getAnnotation(Class<A> annotationClass)
getAnnotations()

**Comment by mirkosertic** [comment]
There are currently no plans for full Reflection API support. But I think the runtime environment can be extended for specific use cases. What are you trying to do with annotations?

**Comment by norzak** [comment]
There is no need to support reflection. We use annotations for application configuration purposes. If you can only make the annotations available as implemented classes, the above methods would just work. For example, I would like to know in the API if @PublicApplication annotation is available or not.

**Comment by mirkosertic** [comment]
I see the point. As a workaround for the current version, the solution could be to just add an marker interface to the class. Existence can be tested at runtime with a simple `instanceof` operation.

**Comment by norzak** [comment]
That is just a simple Annotation, we have complex ones, and the API is cross platform so we can not only accommodate Bytecoder environment. It may be marked as a future enhancement if you would like to get back to it at some point. We will use the annotation processor created for GWT environment for now with Bytecoder.

**Comment by mirkosertic** [comment]
Ok, so we are talking about Annotations with `RetentionPolicy.Runtime`, right? All other annotations are not preserved by the JVM at runtime, and Bytecoder should do the same in this case.

**Comment by norzak** [comment]
Yes, RetentionPolicy.Runtime.

**Comment by mirkosertic** [comment]
Closed due to no further interaction.
