### ISSUE TITLE
request for help:  Extending Canvas2D support

### ISSUE THREAD

**Issue by WhiteHexagon** [mirkosertic/Bytecoder#372]
I have a growing collection of extensions for Canvas2D, but so far they have just been extra methods of attributes.  Now I need to map a class.  I had a look at the user manual, but I dont think it covers this case:

https://developer.mozilla.org/en-US/docs/Web/API/Path2D/Path2D

At first I was thinking that something like this would work:

```
import de.mirkosertic.bytecoder.api.OpaqueReferenceType

class Path2D(d: String) : OpaqueReferenceType
```

but there are multiple constructors to support.  I am still learning Kotlin, but I found something that should cover that case:

```
//    constructor(d: String) : super(d) {}
//    constructor(path: Path2D) : super(path) {}
//    constructor() : super() {}
```
but I don't have a parent object to instantiate.  I had a look at the ArrayBuffer example, but could not work out if that is the right approach, or even how it works.  I also tried in Java, but also failed.  It feels like I should have some parent object here and not just implement what I assume is a marker interface?

Spec:

```
[Exposed=(Window,Worker)]
interface Path2D {
  constructor(optional (Path2D or DOMString) path);

  void addPath(Path2D path, optional DOMMatrix2DInit transform = {});
};
Path2D includes CanvasPath;
```

I had the same issue trying to add  `AudioContext` support.  So any tips would be appreciated.

[edit: same trying to add support for this:]

```
val snd = new Audio("beep.wav")
snd.play()
```

**Comment by mirkosertic** [comment]
Well, you basically need some kind of factory method for the Path2D instances. Take a look at the TypedArray abstraction. There are no constructor invocations, just static native methods returning
opaque references.

```
package de.mirkosertic.bytecoder.api.web;

import de.mirkosertic.bytecoder.api.OpaqueReferenceType;

public abstract class OpaqueArrays {

    public static native IntArray createIntArray(int aLength);

}
```

Now, we need the adapter logic on js side. This all comes down to the following JavaScript. You see here that Opaque Reference Type constructions happens on JS side, not within the WebAssembly module. The logic is imported into the WebAssembly module, but is not implemented there.

```
bytecoder.imports.opaquearrays : {
             createIntArrayINT: function(thisref, p1) {
                 // Magic happens here. JS instance of Int32Array is mapped to JVM/Bytecoder opaque reference here, which is always of type INT
                 return bytecoder.toBytecoderReference(new Int32Array(p1));
             },
         },
```

This pattern can be adapted to Path2D or any other JavaScript object. If you need different or overloaded constructors, just write different factory methods. 

Please note the JS to Bytecoder String Conversion logic as stated in the manual here https://mirkosertic.github.io/Bytecoder/chapter-1/page-1-f/.
`

**Comment by WhiteHexagon** [comment]
thanks! finally I got there :)

So on the Kotlin side I added this:

```
import de.mirkosertic.bytecoder.api.OpaqueReferenceType

abstract class Path2D : OpaqueReferenceType {
    companion object {
        @de.mirkosertic.bytecoder.api.Import(module = "extcanvas", name = "create")
        external fun createPath2D(d: String): Path2D
    }
}
```
Not sure if I need to add a `@JvmStatic` annotation there?

And on the .js side, I did not realise that I needed to implement that, somehow I thought it was magically generated like everything else :)

```
<body id="body">
    <script>
        bytecoder.imports.extcanvas.create = function (thisref, p1) {
            return bytecoder.toBytecoderReference(new Path2D(bytecoder.toJSString(p1)));
        };
        var instantiated = function (result) {
        bytecoder.init(result.instance);
```
Sorry but my javascript skills are rubish, hence my desire to use bytecoder :)  Good that you mentioned the String tip, thanks.

It works :) but I just wanted to check this approach is correct.  Or should I somehow try to inject that bit of .js into the generated binding.js?

**Comment by mirkosertic** [comment]
You have to add `@JvmStatic` to the method to make it static. It doesn't matter in this case for the WASM backend, but the JS backend will not work.

Please do not modify the generated binding.js file. It is generated by the compiler, and not intended to be modified by the user. Please create another JS with user code. It you like, you can use tools like WebPack to combine compiler generated js and user code js, but that's another story. For the moment, either add a script tag with the user code as you've done or create an external js and load it into the document by a script tag.

**Comment by WhiteHexagon** [comment]
btw have you considered adding a generic way of calling javascript?  For example in Go I was using this:

[https://golang.org/pkg/syscall/js/](https://golang.org/pkg/syscall/js/)

example using it:

https://github.com/WhiteHexagon/go-webgl/blob/master/api.go

This avoids having to add the extra .js code for each new bit of functionality.  Just a thought :)

This can be closed.  Thanks.
