### ISSUE TITLE
llvm error

### ISSUE THREAD

**Issue by dguimard** [mirkosertic/Bytecoder#384]
Dear Team
the integration failed during the build :
Cannot run program "llc-10" (in directory "/var/folders/pf/s9g0ytxn68g7g_6cg_mcbg400000gn/T"): error=2, No such file or directory -
[INFO] Bytecoder Parent POM ............................... SUCCESS [  0.306 s]
[INFO] Bytecoder Classlib ................................. SUCCESS [  0.003 s]
[INFO] Bytecoder APIs ..................................... SUCCESS [  0.707 s]
[INFO] Bytecoder java.base Module ......................... SUCCESS [  3.981 s]
[INFO] Bytecoder java.datatransfer Module ................. SUCCESS [  0.056 s]
[INFO] Bytecoder java.xml Module .......................... SUCCESS [  1.770 s]
[INFO] Bytecoder java.desktop Module ...................... SUCCESS [  3.118 s]
[INFO] Bytecoder java.logging Module ...................... SUCCESS [  0.070 s]
[INFO] Bytecoder OpenCL API ............................... SUCCESS [  0.026 s]
[INFO] Bytecoder Web API .................................. SUCCESS [  0.038 s]
[INFO] Bytecoder Vue.js API ............................... SUCCESS [  0.018 s]
[INFO] Bytecoder Core ..................................... SUCCESS [  0.795 s]
[INFO] Bytecoder Maven Plugin ............................. SUCCESS [  2.421 s]
[INFO] Bytecoder Integrationtest .......................... FAILURE [01:03 min]
[INFO] Bytecoder Command Line Interface ................... SKIPPED

any idea?
david

**Comment by mirkosertic** [comment]
Did you install LLVM 10 using the automatic installation script located here : https://apt.llvm.org/ ?

If not, did you just install a tarball? If so, you have to create the symlink named `llc-10` to the `llc` binary in the bin directory of the tarball. You also have to create the symlink named `wasm-ld-10` to the `wasm-ld` binary in the tarball. Please make sure all the symlinks are available in the `PATH` environment variable.

**Comment by mirkosertic** [comment]
Closed due to no further user feedback.
