### ISSUE TITLE
Override/custom code in OpaqueReferenceType extension (in Kotlin)

### ISSUE THREAD

**Issue by WhiteHexagon** [mirkosertic/Bytecoder#396]
So for my Canvas2D extensions, I wanted some TextMetrics information.

I start in the normal way by adding the extra method to my extension interface.

```
interface ExtContext : CanvasRenderingContext2D, CanvasDrawPath {
    fun measureText(text: String): TextMetrics
    ...
}
```

Then I have an interface, mapping some of the properties I need.

```
interface TextMetrics : OpaqueReferenceType {
    @OpaqueProperty
    fun actualBoundingBoxLeft(): Double

    @OpaqueProperty
    fun actualBoundingBoxRight(): Double

    @OpaqueProperty
    fun actualBoundingBoxAscent(): Double

    @OpaqueProperty
    fun actualBoundingBoxDescent(): Double

    fun width(): Double {
        return actualBoundingBoxLeft() + actualBoundingBoxRight()
    }

    fun height(): Double {
        return actualBoundingBoxAscent() + actualBoundingBoxDescent()  //TODO +1??
    }

}
```

I did not want to use the `width` property as provided by TextMetrics, I wanted the above implementation (and custom code for the `height` calculation too).  

So I am wondering if there is an annotation I can use, that my custom helper code gets ignored by bytecoder, since when I call these methods, I currently get an error:

`TypeError: bytecoder.referenceTable[target].width is not a function`

To complicate things there is also a property called width...  but since I dont care to access that, I am happy with my 'override'

[https://developer.mozilla.org/en-US/docs/Web/API/TextMetrics](https://developer.mozilla.org/en-US/docs/Web/API/TextMetrics)

I did think about wrapping the TextMetric in a helper class, but that complicates the definition of `measureText`, since that would also need to return the helper class.  And then I imagine I would end up wrapping all the `OpaqueReferenceType` instances in my own helpers for all my Canvas2D extensions.  Maybe that is what I should be doing anyway, but it seems wasteful...  I hope that makes sense :)  or if you have a better solution please?

**Comment by mirkosertic** [comment]
Have you tried an abstract class for the `TextMetrics` instead of an interface? Maybe the default methods in the interface are handled not correctly, so could you please give the abstract class a try?

**Comment by WhiteHexagon** [comment]
Good idea.  So `abstract class` works.
