### ISSUE TITLE
Optimize memory free operation

### ISSUE THREAD

**Issue by mirkosertic** [mirkosertic/Bytecoder#412]
As reported by #367, there is sometimes some stuttering when running animations. This is related to the GC. After some profiling, it turns out that memory deallocation is very imperformant. The reason is the current memory manager uses a linked list ´to maintain the list of allocated blocks. It takes to long to remove a block from this list. The linked list should be replaced by a double-linked list.

**Comment by WhiteHexagon** [comment]
I was also wondering if there could be a way to track the garbage that is generated within the animation loop.  So besides the effort to improve the GC performance, it would also allow efforts on the developer side to limit the generated garbage.  Maybe by the addition of some bytecoder method calls `startTrackingMemoryAllocations()` and `stopAndListAllocations()` maybe just listing the byte size of each allocation might be enough info for a developer to track it down.  These paired calls could then be wrapped around any performance critical code paths, such as the animation block.  Just an idea :) keep up the good work!

**Comment by mirkosertic** [comment]
Merged to master and closed.
