### ISSUE TITLE
Exporting Java Classes for Javascript

### ISSUE THREAD

**Issue by Nashorn** [mirkosertic/Bytecoder#420]
I see an example of using the @Export decorator to export out methods. But what If i need to export out a series of classes that make-up an API that needs to be exposed to Javascript?
Is this possible?

@Export("JBox2DSimulation");
public class JBox2DSimulation {
    public static void proceedSimulation() {
    }
}

From JS side:
var JBox2DSimulation = bytecoder.exports.JBox2DSimulation;  //class ref

?

**Comment by mirkosertic** [comment]
Closed due to no further interaction.
