### ISSUE TITLE
Lua4J Demo compiled to WebAssembly does not work

### ISSUE THREAD

**Issue by jhoyongpark** [mirkosertic/Bytecoder#431]
This happens from both of webassmebly and webassembly with llvm.
webassembly version: Uncaught RuntimeError: Invalid index into function table.
webassembly-llvm version: Uncaught RuntimeError: unreachable

`lua_wasm.wasm:1 Uncaught RuntimeError: invalid index into function table
    at https://mirkosertic.github.io/Bytecoder/lua_wasm.wasm:wasm-function[33]:0x1081c
    at https://mirkosertic.github.io/Bytecoder/lua_wasm.wasm:wasm-function[2317]:0x6b8b8
    at https://mirkosertic.github.io/Bytecoder/lua_wasm.wasm:wasm-function[2314]:0x6b3d7
    at https://mirkosertic.github.io/Bytecoder/lua_wasm.wasm:wasm-function[2313]:0x6b009
    at https://mirkosertic.github.io/Bytecoder/lua_wasm.wasm:wasm-function[2326]:0x6be1d
    at https://mirkosertic.github.io/Bytecoder/lua_wasm.wasm:wasm-function[2261]:0x6835c
    at https://mirkosertic.github.io/Bytecoder/lua_wasm.wasm:wasm-function[2260]:0x681a4
    at https://mirkosertic.github.io/Bytecoder/lua_wasm.wasm:wasm-function[2256]:0x67d4e
    at https://mirkosertic.github.io/Bytecoder/lua_wasm.wasm:wasm-function[2220]:0x65ef3
    at https://mirkosertic.github.io/Bytecoder/lua_wasm.wasm:wasm-function[2218]:0x65ad5

lua_wasmllvm.wasm:1 Uncaught RuntimeError: unreachable
    at malloc (https://mirkosertic.github.io/Bytecoder/lua_wasmllvm.wasm:wasm-function[4147]:0x74627)
    at newObject (https://mirkosertic.github.io/Bytecoder/lua_wasmllvm.wasm:wasm-function[431]:0x7e22)
    at newArrayINTINTINT (https://mirkosertic.github.io/Bytecoder/lua_wasmllvm.wasm:wasm-function[3694]:0x68bf4)
    at https://mirkosertic.github.io/Bytecoder/lua_wasmllvm.wasm:wasm-function[3765]:0x6a922
    at https://mirkosertic.github.io/Bytecoder/lua_wasmllvm.wasm:wasm-function[633]:0xe0a5
    at https://mirkosertic.github.io/Bytecoder/lua_wasmllvm.wasm:wasm-function[3763]:0x6a84d
    at https://mirkosertic.github.io/Bytecoder/lua_wasmllvm.wasm:wasm-function[2194]:0x3077a
    at https://mirkosertic.github.io/Bytecoder/lua_wasmllvm.wasm:wasm-function[1956]:0x2c049
    at https://mirkosertic.github.io/Bytecoder/lua_wasmllvm.wasm:wasm-function[2935]:0x4467b
    at https://mirkosertic.github.io/Bytecoder/lua_wasmllvm.wasm:wasm-function[2929]:0x43fe8`

**Comment by mirkosertic** [comment]
Fixed with Release 2020-07-29. It was a subtle bug in the garbage collector logic.
