### ISSUE TITLE
Passing Mixed Array Object to Javascript 

### ISSUE THREAD

**Issue by norzak** [mirkosertic/Bytecoder#433]
Is there a way to pass a mixed object array that consists of only  numbers, booleans and strings to Javascript. I looked in to OpaqueReferenceArray but I do not think it is possible to do this with it in its current form.

**Comment by mirkosertic** [comment]
I don't think so. The JVM cannot create arrays of mixed type, e.g. primitives(int, long, boolean...) and java.lang.Object. So we cannot create such kind of array, and no API is needed to pass this to JS side.

**Comment by norzak** [comment]
How about new Object[]{"Hello", 1, true, 3.5}. Numbers and booleans are autoboxed by Compiler.

**Comment by mirkosertic** [comment]
Primitives are Autoboxed on Wasm-Side and are not automatically Unboxed on JS side. However, you can always pass the array-reference from Wasm to JS and use JS to access the array elements one by one. Take a look at https://mirkosertic.github.io/Bytecoder/chapter-3/page-3-b/ for the Wasm memory layout.

**Comment by mirkosertic** [comment]
Closed due to no further interaction.
