### ISSUE TITLE
Hello world in Clojure

### ISSUE THREAD

**Issue by danielsz** [mirkosertic/Bytecoder#438]
This is an amazing project. Thank you for sharing this with the world. 

I've tried to compile a hello world program with Clojure, and encountered an issue that comes up when Clojure itself is being compiled. 

```java
[ERROR] Failed to execute goal de.mirkosertic.bytecoder:bytecoder-mavenplugin:2020-07-29:compile (default) on project bar: Error running bytecoder: Error linking class bar.core: Error linking class clojure.lang.RT: Error linking class clojure.lang.Compiler: Error linking class clojure.lang.Reflector: Cannot find static method lookup in java/lang/invoke/MethodHandles with signature java.lang.invoke.MethodHandles$Lookup() -> [Help 1]
```
It is an issue that also came up previously when people tried to use the Graal native image on Clojure code. The good news is that the fix is known, the bad news is that the latter is enabled by a GraalVM feature called `substitutions`.

The comprehensive description + fix was submitted by @borkdude and I'll cite the reference here: https://github.com/oracle/graal/issues/2214

It would be awesome if we could get past this hurdle and compile Clojure to `wasm`. Thank you in all cases!

**Comment by borkdude** [comment]
The substitutions are only needed for Java 11. An alternative approach is to copy clojure.lang.Reflector.java into your own project and patch accordingly.

**Comment by danielsz** [comment]
What worked for me is patching Clojure itself and then referencing the patched Clojure in my project. That got rid of the error I mentioned earlier. On to the next!

```java
[ERROR] Failed to execute goal de.mirkosertic.bytecoder:bytecoder-mavenplugin:2020-07-29:compile (default) on project bar: Error running bytecoder: Error linking class bar.core: Error linking class clojure.lang.RT: Error linking class clojure.lang.Compiler: Cannot find virtual method compareAndSet in non-abstract class java/util/concurrent/atomic/AtomicReference with signature BOOLEAN(java.lang.Object,java.lang.Object) -> [Help 1]
```
Any idea? This feels like going down a rabbit hole :-)

**Comment by mirkosertic** [comment]
@danielsz thank you for your kind feedback!

Bytecoder already has a substitution logic, it is used to path some JRE classes.

Is your hello-world example available for download? I'd like to see what can be done!

**Comment by danielsz** [comment]
Oh, neat, I wasn't aware of that. I did read the manual :-) Have I missed it? Is it documented? Thanks!

My [changes](https://github.com/clojure/clojure/compare/master...danielsz:bytecoder) in the Clojure source code is to be found in on my [fork](https://github.com/danielsz/clojure). This gets past the first error. 

There is nothing special to the `hello world` program, but I prepared a [repo](https://github.com/danielsz/bytecoder-clojure) for you in case you're not familiar with the ecosystem. The `deps.edn` file is an [officially sanctioned](https://clojure.org/guides/deps_and_cli) way to declare dependencies and build a classpath. The `meyvn.edn` file is the configuration for the [meyvn](https://meyvn.org) build tool  (of which I am the author). Despite Clojure being compilable via a Maven plugin, this is not the path the community went down. Meyvn is using Maven directly. My tool is not open source, but it is free to use. Feel free to investigate the community standards for building a Clojure project. Please let me know if there is anything I can help you with.

**Comment by mirkosertic** [comment]
I've done some tests with Clojure, and I'm afraid Bytecoder won't be able to handle Clojure generated JVM bytecode properly.

The main reason is the Clojure runtime and its dependencies. It relies heavily on JVM Reflection API, which is supported by Bytecoder only in a very limited form. See https://mirkosertic.github.io/Bytecoder/chapter-1/page-1-d/ for more information about Reflection API support.

**Comment by danielsz** [comment]
Totally makes sense. Thank you for doing the research and sharing this with us. Yours is an awesome project regardless.
