### ISSUE TITLE
Canvas 2D and WebGL support missing

### ISSUE THREAD

**Issue by norzak** [mirkosertic/Bytecoder#444]
The Canvas 2D support is very limited and WebGL is not available at all. I think offering these two in the core is very important.

**Comment by CoenRijsdijk** [comment]
I ran into the same problem, but yet i have found a solution. You can make your own types and make WebGL work, example can be found here: https://github.com/squins/libgdx-wasm-with-bytecoder

The example is still simple and small, but it works with webgl. I'm still working on it.
Hope that you find it useful!

**Comment by norzak** [comment]
It looks like it is easy to implement our own with Opaque Reference Types.
