### ISSUE TITLE
OpenCL: double type not supported yet?

### ISSUE THREAD

**Issue by andi-huber** [mirkosertic/Bytecoder#459]
From the Mandelbrot example, when using **double** instead of **float** for the kernel, 

```

    private double x_min;
    private double y_min;
    private double x_max;
    private double y_max;
    ...
    private double cellSize_width;
    private double cellSize_height;
    ...

    private int checkC(final double reC, final double imC) {
        double reZ=0,imZ=0,reZ_minus1=0,imZ_minus1=0;
        ...    
    }

    @Override
    public void processWorkItem() {
        final int pixelIndex = get_global_id(0);
        final int x = pixelIndex % width;
        final int y = pixelIndex / width;

        final double reC = x_min + (x * cellSize_width); 
        final double imC = y_min + (y * cellSize_height);

        imageData[pixelIndex] = checkC(reC, imC);
    }
```

I do get an exception:

```
java.lang.IllegalArgumentException: Type DOUBLE is not supported for kernel argument cellSize_height
	at de.mirkosertic.bytecoder.backend.opencl.OpenCLContext.compute(OpenCLContext.java:269)
	... 3 more
```

https://github.com/mirkosertic/Bytecoder/blob/d658140671fbef46838597d5597663ec1cdb4958/core/src/main/java/de/mirkosertic/bytecoder/backend/opencl/OpenCLContext.java#L269

Is data type double not supported yet, or is this a bug?

Cheers!

**Comment by andi-huber** [comment]
I also just realized, that double (=float64) is only optional as of OpenCL spec 2.2:
https://www.khronos.org/registry/OpenCL/specs/2.2/html/OpenCL_C.html

**Comment by mirkosertic** [comment]
Hi! Thank you for using Bytecoder!

Indeed, the `double` datatype is optional, so I didn't implement support for it in the first place. Also `float` calculations are much faster on some/most devices, so there wasn't need for it till now.

What are you planning to do?

**Comment by andi-huber** [comment]
I'm using kernels with double precision and also arrays of type short. I was able to easily extend the above mentioned class to support the remaining java primitive types. Want me to create a PR?

Also I noticed for OpenCL your library would not yet support java 15 compliance level. Again by simply adding one line of code all just worked great. Could create a PR seperately for that one as well.

**Comment by mirkosertic** [comment]
PR's are always very welcome ;-)

**Comment by mirkosertic** [comment]
I've merged this PR to master. Thank you for your contribution!

If you like, I will create a new release with this change and push it to Maven Central.

**Comment by andi-huber** [comment]
Thx! I also have a perfomance suggestion for `CPUContext`. That is to use Java's ForkJoinPool instead. If you like I can make another PR for that. If not I'm happy to see a new release. Let me know.

```
public class CPUContext implements Context {

    private final Logger logger;

    public CPUContext2(Logger aLogger) {
        logger = aLogger;
    }

    @Override
    public void compute(int aNumberOfStreams, Kernel aKernel) {
        
        IntStream.range(0, aNumberOfStreams)
        .parallel()
        .forEach(workItemId->{
            try {
                set_global_size(0, aNumberOfStreams);
                set_global_id(0, workItemId);
                aKernel.processWorkItem();
            } catch (Exception e) {
                throw new IllegalStateException("Something went wrong", e);
            }
        });

    }

    @Override
    public void close() {
        // cannot stop a stream from executing
    }
}
```

**Comment by mirkosertic** [comment]
Feel free to submit a new PR for the ForkJoinPool improvement. You would create a ForkPoinPool per Kernel, right? Are you planning to run multiple Kernels at the same time and to get around the parallel() limitation of the Streams API?

**Comment by andi-huber** [comment]
Nope, we would just use the common ForkPoinPool `(ForkPoinPool.common())` which in my experience, is a reasonable choice for a default implementation. Users can always override this. 

Alright, I'll create a PR then. Possibly later today.
