### ISSUE TITLE
OpenCL/CPUContext: use the Common ForkJoinPool instead of a FixedThreadPool 

### ISSUE THREAD

**Issue by andi-huber** [mirkosertic/Bytecoder#462]
This is a performance enhancement suggestion.
PR follows.

**Comment by mirkosertic** [comment]
The PR is merged. Shall I create a new release, or you do have other suggestions into your pipeline ;-) ?

**Comment by andi-huber** [comment]
No new suggestions at the moment. :) Thx for merging!
