### ISSUE TITLE
Cannot find virtual method nextLong in non-abstract class java/util/Random with signature LONG() 

### ISSUE THREAD

**Issue by CoenRijsdijk** [mirkosertic/Bytecoder#465]
I'm trying a to port a libgdx app written in Kotlin to the web with Bytecoder.

I'm running into the following problem, when I instantiate a libgdx SpriteBatch --> https://github.com/squins/libgdx-wasm-with-bytecoder/blob/master/libgdx-app/core/src/com/mygdx/game/MyGdxGame.kt      line 13/14

```
Error linking class com.badlogic.gdx.graphics.glutils.ShaderProgram: Error linking class com.badlogic.gdx.math.MathUtils: Cannot find virtual method nextLong in non-abstract class java/util/Random with signature LONG() -> [Help 1]
```
![image](https://user-images.githubusercontent.com/33197611/94281057-72fdf780-ff4e-11ea-9740-05edb96cd0d2.png)

**Comment by mirkosertic** [comment]
Thank you for reporting this bug. I will try to provide a fix as soon as possible.

**Comment by CoenRijsdijk** [comment]
Hi,

This is a blocking issue for us. Is there anything we can do to help, or is it really only possible to solve this with extensive Bytecode(r) knowledge?

Is there any workaround available for this?

Thanks in advance for your reaction.

**Comment by mirkosertic** [comment]
A fix is on its way ;-)

**Comment by CoenRijsdijk** [comment]
Bug fixed
