### ISSUE TITLE
Cannot find virtual method putIntUnaligned in non-abstract class jdk/internal/misc/Unsafe with signature VOID(java.lang.Object,LONG,INT,BOOLEAN)

### ISSUE THREAD

**Issue by CoenRijsdijk** [mirkosertic/Bytecoder#467]
Found new bug after re-instantiating SpriteBatch. Follow up: https://github.com/mirkosertic/Bytecoder/issues/465
![image](https://user-images.githubusercontent.com/33197611/95079253-a2fb8680-0716-11eb-9e2e-08714291ddbf.png)

Is it possible you will rebuild our project after the fix and see if it is fixed?
https://github.com/squins/libgdx-wasm-with-bytecoder

**Comment by keesvandieren** [comment]
We've forked and added missing methods. 

We now get follow up errors, which are probably related to other issues. The error is:

```
Uncaught (in promise) TypeError: WebAssembly.instantiate(): Import #30 module="bufferutils" error: module is not an object or function
```

When we do not create an instance of `SpriteBatch`, log statements we have in code before instantiating a SpriteBatch, appears. Once we activate SpriteBatch, log statements in the code before creating SpriteBatch are not appearing; are log-statements buffered, before they are sent to JS console.log?

How we used our own methods:

* cloned Bytecoder repo
* run mvn `install -DskpiTests` on bytecoder repo
* set bytecoder.version in our own Maven project to 0-SNAPSHOT
* in libgdx-wasm-with-bytecoder/libgdx-sample-app, run `gradlew publishToMavenLocal`
* in libgdx-wasm-with-bytecoder, run `mvn clean install`
* start IDEA webserver in libgdx-wasm-with-bytecoder/libgdx-wasm-with-bytecoder-example/target/bytecoder/, preview index.html

Is this approach correct? Should Bytecoder use new methods correctly in this way? 

If you would like to try what I tried, here is the code: https://github.com/squins/libgdx-wasm-with-bytecoder/tree/tryouts-kees/libgdx-sample-app

**Comment by tommyettinger** [comment]
Is the original Unsafe compile error related to https://github.com/mirkosertic/Bytecoder/blob/master/classlib/java.base/src/main/resources/META-INF/modules/java.base/classes/java/nio/Heap-X-Buffer.java.template being a template and not complete Java? I didn't see any other usage of putIntUnaligned(). It's pretty cool that Bytecoder implements the JVM so deeply that even internals are mostly the same.

**Comment by tommyettinger** [comment]
Digging a little deeper, it's very odd that `bufferutils` is all lower-case; it may or may not be related to https://github.com/libgdx/libgdx/blob/master/backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/com/badlogic/gdx/utils/BufferUtils.java (which is emulated on GWT by the libGDX GWT backend, and might need to be aded to the libGDX Bytecoder backend in the squins repo, too). I don't know if Bytecoder has a mechanism like GWT's super-source emulation.

**Comment by keesvandieren** [comment]
@mirkosertic  are you able to provide some pointers / suggestions for us :)?

**Comment by keesvandieren** [comment]
I've placed a reaction here: #293 

We've a solution for bufferutils problem.

The other problem, https://github.com/squins/Bytecoder/commit/71b80a3c469310c81d6e39fdd491b39662513468 we can make a PR for this.

**Comment by keesvandieren** [comment]
We've submitted PR #474 which resolves this issue.

However, some builds fail with this
