### ISSUE TITLE
Why is Class.getSimpleName() not implemented?

### ISSUE THREAD

**Issue by keesvandieren** [mirkosertic/Bytecoder#483]
We found that one of the libraries our project is using, is calling `Class.getSimpleName()`.

It seems to be not implemented in Bytecoder.

What is the reason for this?

**Comment by CoenRijsdijk** [comment]
We have implemented it on a branch, but we are not sure if it is the right way.
Commits: 

https://github.com/squins/Bytecoder/commit/42a106eb86e6b4b4d08d075aec4abce756b1a45b
https://github.com/squins/Bytecoder/commit/667b942064b22fad335ce7e38dad09656d919e91
https://github.com/squins/Bytecoder/commit/c972e5df4d53a907a79e1a737f679b793901abf3

**Comment by mirkosertic** [comment]
Merged to master
