### ISSUE TITLE
Pattern.compile working on JVM does not work with Bytecoder

### ISSUE THREAD

**Issue by CoenRijsdijk** [mirkosertic/Bytecoder#489]
**Pattern 1:** `Pattern.compile("^[a-zA-Z_$][a-zA-Z_$0-9]*$")`
**Pattern 2:** `Pattern.compile("^[^\":,}/ ][^:]*$")`

These patterns are used in Libgdx. It does work on JVM, however Pattern 1 does not work with Bytecoder and Pattern 2 does.

https://github.com/squins/Bytecoder/tree/reproduce-pattern-issue

``` java
package com.example;

import java.util.regex.Pattern;

public class Main {
    public static void main(String[] args) {
        System.out.println("Before Pattern call");
        Pattern javascriptPattern = Pattern.compile("^[a-zA-Z_$][a-zA-Z_$0-9]*$");
        System.out.println("After Pattern call");
    }
}
```

**Comment by mirkosertic** [comment]
Fix merged to master.
