### ISSUE TITLE
Using soot for java IR

### ISSUE THREAD

**Issue by enleeten** [mirkosertic/Bytecoder#49]
Bytecoder looks like a cool project. Have you considered using one of [Soot](https://github.com/Sable/soot)'s representations for the IR aspect?

**Comment by mirkosertic** [comment]
I looked at Soot and other IR's such as LLVM. For now I am fine with the current implementation. Main goal of Bytecoder is to provide a cross compiler for other platforms. Optimizations can be done *before* running Bytecoder (Soot or other frameworks), or *after" Bytecoder is finished (Google Closure Compiler or Binaryen).

**Comment by enleeten** [comment]
Cool, I look forward to following Bytecoder!
