### ISSUE TITLE
Enabling preview features doesn't work with maven

### ISSUE THREAD

**Issue by CC007** [mirkosertic/Bytecoder#497]
I tried to enable preview features for java 14, so that I can use text blocks with the following config:
```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.8.1</version>
    <configuration>
        <release>14</release>
        <encoding>${project.build.sourceEncoding}</encoding>
        <compilerArgs>
            <arg>--enable-preview</arg>
        </compilerArgs>
    </configuration>
</plugin>
```
But this causes the bytecoder-mavenplugin to fail:
```
[ERROR] Failed to execute goal de.mirkosertic.bytecoder:bytecoder-mavenplugin:2020-12-01:compile (default) on project WebAssemblyPOC: Execution default of goal de.mirkosertic.bytecoder:bytecoder-mavenplugin:2020-12-01:compile failed: An API incompatibility was encountered while executing de.mirkosertic.bytecoder:bytecoder-mavenplugin:2020-12-01:compile: java.lang.UnsupportedClassVersionError: Preview features are not enabled for com/github/cc007/webassemblypoc/OpaqueReferenceTest (class file version 58.65535). Try running with '--enable-preview'
```
I have that plugin configured as follows:
```xml
<plugin>
    <groupId>de.mirkosertic.bytecoder</groupId>
    <artifactId>bytecoder-mavenplugin</artifactId>
    <version>2020-12-01</version>
    <configuration>
        <mainClass>com.github.cc007.webassemblypoc.OpaqueReferenceTest</mainClass>
        <backend>wasm</backend>
        <enableExceptionHandling>false</enableExceptionHandling>
        <optimizationLevel>ALL</optimizationLevel>
        <buildDirectory>target/classes</buildDirectory>
    </configuration>
    <executions>
        <execution>
            <goals>
                <goal>compile</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```
I couldn't find any documentation on how to configure that plugin to pass the --enable-preview flag.

If there is a way, could you add this to your documentation?

If it is not possible yet, could you add the ability to pass along such a flag?

**Comment by mirkosertic** [comment]
Hey! Thank you for trying Bytecoder!
Do you have a Git repository where I can check out the example? I'd like to track it down...

**Comment by CC007** [comment]
It is the same repo as I used in #499, but I have removed the preview argument now. Putting it back and adding a text block (those with """) should trigger the error

**Comment by CC007** [comment]
[this repo](https://github.com/CC007/WebAssemblyPOC/blob/master/src/main/java/com/github/cc007/webassemblypoc/OpaqueReferenceTest.java) to be exact. I tried using it for the html part

**Comment by mirkosertic** [comment]
I've checked your example repository.

You have to pass the `--enable-preview` Flag to Maven as well, so the Maven classloader are allowed to read bytecode with preview features. The classloader is used by the Bytecoder plugin to get class file data.

**Comment by CC007** [comment]
Thanks. I am using IntelliJ, so I was able to add --enable-preview to VM Options (In the Runner tab of the run configuration) to achieve the same thing.

**Comment by CC007** [comment]
Also, for me the problem is also resolved by using java 15, since text blocks are now part of the core language. For future experimental features it is nice to know how to fix this though. :)
