### ISSUE TITLE
[BUG] Error running bytecoder when using BigDecimal (and BigInteger issues)

### ISSUE THREAD

**Issue by CC007** [mirkosertic/Bytecoder#498]
I created a simple 'click me' application that increments a counter whenever I click a certain part of the screen and compiled it to wasm. This works nicely, but when I try to replace the integer that I use to increment the counter with a BigDecimal, I get the followig error:
```
...
[INFO] Linked sun.nio.cs.UnicodeEncoder
[INFO] Linked sun.nio.cs.UTF_16$Encoder
[INFO] Linked java.math.MutableBigInteger
[INFO] Linked java.lang.ArrayIndexOutOfBoundsException
[INFO] Linked java.math.BigDecimal$StringBuilderHelper
[IJ]-1-MojoFailed-[IJ]-source=LIFECYCLE-[IJ]-goal=compile-[IJ]-id=com.github.cc007:WebAssemblyPOC:jar:1.0.0-SNAPSHOT-[IJ]-error=Failed to execute goal de.mirkosertic.bytecoder:bytecoder-mavenplugin:2020-12-01:compile (default) on pr
oject WebAssemblyPOC: Error running bytecoder
[IJ]-1-ProjectFailed-[IJ]-id=com.github.cc007:WebAssemblyPOC:jar:1.0.0-SNAPSHOT
[IJ]-1-SessionEnded-[IJ]-id=unknown
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
...
```
I reverted back to the integer implementation and it worked again. When I then just added `BigDecimal decimal = BigDecimal.ONE;` somewhere in the code, without using it, I got the same error above again. 

This let me to believe that something is going wrong when trying to compile BigDecimal to wasm

I tried doing the same with BigInteger, and while that did compile, it did give the wrong result: trying to add 1 to the number actually subtracted 2.

### Platform
OS: Windows 10 (version 2004, build 19041.685)
Browser: Firefox 84.0.1
Java: OpenJDK 14.0.2
Bytecoder dep/plugin: 2020-12-01

**Comment by mirkosertic** [comment]
Fix merged to master branch.

**Comment by CC007** [comment]
Nice! When is the next release planned?

**Comment by CoenRijsdijk** [comment]
If you want to try it out you could clone Bytecoder, build master with mvn install -DskipTests and set Bytecoder version in your pom.xml to SNAPSHOT-0 😃. And then set next release, Bytecoder version to new version
