### ISSUE TITLE
[BUG] Error running bytecoder when using JSONObject

### ISSUE THREAD

**Issue by adeline18** [mirkosertic/Bytecoder#505]
I creeated a class, code like this:

import org.json.JSONObject;
JSONObject params = new JSONObject();

run bytecode maven plugin ,then an error occured:
java.lang.IllegalStateException: Cannot find virtual method getPackage in non-abstract class java/lang/Class with signature java.lang.Package()

**Comment by mirkosertic** [comment]
Hey! Thank you for using Bytecoder!

**Comment by adeline18** [comment]
Code like this: 

`package main;
import de.mirkosertic.bytecoder.api.Export;
import org.json.JSONObject;
import java.util.function.Function;

public class Bridge {
    private static JSONObject callBacks = new JSONObject();
    private static long uniqueId = 1;

    public static void main(String[] args) {
    }

    @Export("callNative")
    public static void callNative () {
        JSONObject params = new JSONObject();
    }
}`

maven plugin Configuration file：

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>byteCodeDemo</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>de.mirkosertic.bytecoder</groupId>
            <artifactId>bytecoder.api</artifactId>
            <version>2020-12-01</version>
        </dependency>
        <dependency>
            <groupId>de.mirkosertic.bytecoder</groupId>
            <artifactId>bytecoder.web</artifactId>
            <version>2020-12-01</version>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20201115</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>de.mirkosertic.bytecoder</groupId>
                <artifactId>bytecoder-mavenplugin</artifactId>
                <version>2020-10-05</version>
                <configuration>
                    <mainClass>main.Bridge</mainClass>
                    <filenamePrefix>main</filenamePrefix>
                    <backend>wasm</backend>
                    <enableExceptionHandling>false</enableExceptionHandling>
                    <optimizationLevel>ALL</optimizationLevel>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>`

**Comment by adeline18** [comment]
Can you see any problems? @mirkosertic

**Comment by mirkosertic** [comment]
Closed due to no further interaction.
