### ISSUE TITLE
[LCM] Add official support for java 15

### ISSUE THREAD

**Issue by CC007** [mirkosertic/Bytecoder#509]
Your readme states support for upto java 14. My initial findings seem to be that I have not found any regressions between 14 and 15, but I don't have a full test suite. 

Could you test the use of java 15 more thoroughly and if all is ok, state support for java 15 in your readme?

**Comment by mirkosertic** [comment]
I've merged the OpenJDK 15 Classlibs to the master branch and modified the documentation. The upcoming Bytecoder release will officially support Java 15,
