### ISSUE TITLE
Command line compilation without maven?

### ISSUE THREAD

**Issue by norzak** [mirkosertic/Bytecoder#51]
If the project does not have too many dependencies, in the future, would it be possible to supply a simpler command line compilation as well so that we can use it with our own build tool?

**Comment by mirkosertic** [comment]
Currently, there are only a few dependencies required, so yes, that should be possible? What kind of build tool are you planning to use? If you can't use Maven or Gradle or SBT, maybe I can provide a stand-alone fat JAR to do the job,

**Comment by norzak** [comment]
Excellent. We have been using ant and our build process is quite complex. We need fine grained control over build process. If you can include that in your future releases, that would be great. I will follow your project and hope to see it becomes something awesome.
