### ISSUE TITLE
Cannot find static method parseLong in java/lang/Long with signature LONG(java.lang.CharSequence,INT,INT,INT)

### ISSUE THREAD

**Issue by Vojtasii** [mirkosertic/Bytecoder#514]
Hello, while trying to compile my application written in Kotlin and Java, I have run into this problem. One of the libraries I am using is using the Long.parseLong(name, beginIndex, endIndex, radix) method, which causes the error in the title.

Integer.parseInt with the same signature seems to be working just fine.

Minimal example, Bytecoder version 2021-01-26

```Java
package bytecodertest;

public class LongerParser {
    public static void main(String[] args) {
        long a = Long.parseLong("aa121", 0, 3, 16);
        System.out.println(a);
    }
}
```

**Comment by mirkosertic** [comment]
Fix merged to master and will be part of the next release.
