### ISSUE TITLE
Instanceof and hashcode on any Class (without a instantion) causes a crash

### ISSUE THREAD

**Issue by CoenRijsdijk** [mirkosertic/Bytecoder#528]
While working on gdx-backend-bytecoder I ran into some problems: hascode() and instanceof calls do not work on Class objects.
Down below you can see it how I use reproduce this in simple code:
![image](https://user-images.githubusercontent.com/33197611/110817454-99a9b380-828c-11eb-93d0-0a59f2908b1d.png)

Also you can checkout our research branch: https://github.com/squins/Bytecoder/tree/issue-class-hashcode-and-instanceof
And check https://github.com/squins/Bytecoder/blob/issue-class-hashcode-and-instanceof/issue-research/src/main/java/com.example/Main.java (line 37 till 41)

**Comment by keesvandieren** [comment]
Hi, this issue is currently a showstopper for us. Would be nice if this can be resolved :-)

**Comment by mirkosertic** [comment]
Released with 2021-06-24 and will be available in Maven Central soon.
