### ISSUE TITLE
Bytecoder should be able to run Annotation processors

### ISSUE THREAD

**Issue by norzak** [mirkosertic/Bytecoder#53]
In some cases, we would like to also generate the "index.html" or some auxiliary javasript files that would be used with the compiler generated JavaScript file by processing some in-source annotations of our own. Bytecoder should be able to run the annotation processor if one detected in the jar file.

**Comment by mirkosertic** [comment]
Hmm, this is an interesting concept. Bytecoder currently does not support annotation processors, as it is not a plugin of a Java compiler, but a product in its own. Maybe we can implement annotation processing light by defining some custom interfaces. I don't think we can support the full compiler annotation processing power yet....

**Comment by mirkosertic** [comment]
Closed due to inactivity.
