### ISSUE TITLE
Export Annotation

### ISSUE THREAD

**Issue by norzak** [mirkosertic/Bytecoder#54]
Calling the method with multiple parameters becomes too verbose when a Java method is exported. Could it be much easier to just alias the annotated name to the verbose one? Such as,

```
public class JBox2DSimulation {
    @Export("proceedSimulation")
    public static void proceedSimulation(int a,int b,double c,double d,float e,float f) {
    }
}
```

instead of calling JBox2DSimulation.VOIDproceedSimulationINTINTDOUBLEDOUBLEFLOATFLOAT
from host environment, just calling the annotated "proceedSimulation" that is made available to the window object can be much more clear and easier. For this purpose, another annotation may as well be provided keeping the currently implemented, one such as "Alias".

**Comment by norzak** [comment]
Providing an inline JavaScript implementation that exists in bck2brws and teavm, could also clear many implementation use cases however a JavascriptObject class may be required.

**Comment by mirkosertic** [comment]
The WASM module system already uses the names from the Export annotation. Maybe we can create the same functionality for the JS runtime.

**Comment by norzak** [comment]
Mirko, I think the bck2brw/TeaVM approach needs to be included for better encapsulation. This way, instead of writing exported methods by hand to the bootstrapper page, they may be automatically included in the generated code. 

```
  @JSBody(params = {"msg"}, script = "console.log(msg);")
   static native void console(String msg);
```

My suggestion for an additional annotation as follows
 
```
@JSExport(params = {"msg"}, body = "console.log(msg);")
 static native void console(String msg);
```
A JavascriptObject must also be provided so that "this" can be passed to the inlined method.

**Comment by mirkosertic** [comment]
Exported JavaScript methods are now available using the bytecoder.exports global associative array, which maps the Export name to the internal function reference.

**Comment by norzak** [comment]
Great, but how does it work now? how do you map the method arguments between the Java native method and JavaScript. Could give give an example?

**Comment by mirkosertic** [comment]
I updated the INTEROP documentation, as seen here: https://github.com/mirkosertic/Bytecoder/blob/master/INTEROP.md

**Comment by norzak** [comment]
How are the strings handled when target is WebAssembly with INTEROP? Is it automatic?
