### ISSUE TITLE
Cannot find virtual method getDeclaredField

### ISSUE THREAD

**Issue by jespertheend** [mirkosertic/Bytecoder#549]
Hi, I'm trying to port [closure compiler](https://github.com/google/closure-compiler) to wasm.
I'm currently running into an error: `Caused by: java.lang.IllegalStateException: Cannot find virtual method getDeclaredField in non-abstract class java/lang/Class with signature java.lang.reflect.Field(java.lang.String)` when compiling to wasm.
If I understand correctly this is currently working as intended, since reflection is a hard problem to solve.
Are there any plans for supporting `getDeclaredField` in the future, or is it out of the question?

Closure compiler is a big project so who knows what issues I'll run in to next. So it might very well be an impossiblo task.

**Comment by mirkosertic** [comment]
Hey!
Thank you for using Bytecoder!
Indeed `Class.getDeclaredField(String)` is currently not supported. However, you can always call `Class.getDeclaredFields()` to get all the Fields available AND configured for reflective access.
Porting the Closure compiler to wasm is a HUGE task, so this will not be the last problem you are hitting for sure.

**Comment by jespertheend** [comment]
Ah cool, thanks for the info!
I was hoping not to have to change the closure compiler code too much.
Since I'm not too familiar with Java, and since I'm still not sure if porting closure compiler is a achievable with one person, I've decided to drop the project for now. I'm simply connecting to a local websocket that runs closure compiler for the time being.
But I might revisit this in the future.

**Comment by mirkosertic** [comment]
Cool! Please let me know it you want to get into this task again. I'm always glad to help. I'm closing this ticket for now.
