### ISSUE TITLE
Can you use this tool from the command line?

### ISSUE THREAD

**Issue by ricmf** [mirkosertic/Bytecoder#59]
Can you use the javascript transpiler from the command line, specifying a jar file or build directory? I'd like to try this on my project but i don't use maven and the readme only has info about the maven plugin.

**Comment by mirkosertic** [comment]
Only Maven is supported at the moment, but there is a "Tools" abstraction that can be used the create any kind of tooling integration. Just take a look at https://github.com/mirkosertic/Bytecoder/blob/master/maven/src/main/java/de/mirkosertic/bytecoder/maven/BytecoderMavenMojo.java#L120, there you see how to invoke the tooling api.

If you'd like, you can provide a PR for this!
