### ISSUE TITLE
Commit 7b0e94034b7ffcb11eeccd00db28f117a6b929d6 fails to compile

### ISSUE THREAD

**Issue by kittylyst** [mirkosertic/Bytecoder#60]
On MacOs 10.11.1 with Java 8u144, the build fails out of the box.

mvn compile fails with this exception:
java.io.IOException: No plugin descriptor found at META-INF/maven/plugin.xml

when trying to build integrationtest

**Comment by mirkosertic** [comment]
Hmm, interesting. Which Maven Version are you using?

**Comment by kittylyst** [comment]
$ mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T16:41:47+00:00)
Maven home: /opt/maven
Java version: 1.8.0_144, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.1", arch: "x86_64", family: "mac"

**Comment by kittylyst** [comment]
Interestingly, mvn install fails in a different place to mvn compile (possibly gets further)

**Comment by mirkosertic** [comment]
Maven 3.5.0 does the trick. I've tested it with Oracle JDK 1.8.0_131 and JDK 9 on my Windows 10 machine.

Please run:  `mvn clean install -P notest` to compile from the sources. The "notest" profile disables unit testing.  I am sorry about this but there are some tests that are a little bit fragile at the moment.
