### ISSUE TITLE
Failed to execute goal de.mirkosertic.bytecoder:bytecoder-mavenplugin: Error running bytecoder: Cannot find virtual method getPackage in non-abstract class java/lang/Class with signature java.lang.Package()

### ISSUE THREAD

**Issue by varunManjula** [mirkosertic/Bytecoder#733]
Hi @mirkosertic, thanks for ByteCoders,  

Actually I am facing one issue in importing dependency and trying to convert to JS. 
Attaching a screenshot for reference. 
Could u plz help here. 

<img width="376" alt="image" src="https://user-images.githubusercontent.com/102520225/171417451-5a54bc1e-a60a-4080-8f59-57004f5d5277.png">

**Comment by mirkosertic** [comment]
Closed due to no further feedback.
