### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by ebremer** [mirkosertic/Bytecoder#74]
I'm trying to do a simple java->javascript conversion and I got the following error:

Failed to execute goal de.mirkosertic.bytecoder:bytecoder-mavenplugin:2018-11-29:compile (default) on project trans: Error running bytecoder: de.mirkosertic.bytecoder.integrationtest.SimpleMainClass -> [Help 1]

**Comment by mirkosertic** [comment]
Can you please attach the whole build log?

Also, if you are trying to compile your own provided class, please change the classname in the plugin configuration accordingly to your own class. At the moment it seems to be configured to 
`de.mirkosertic.bytecoder.integrationtest.SimpleMainClass`.

**Comment by ebremer** [comment]
That was the problem.
