### ISSUE TITLE
How to compile JEdit to JavaScript?

### ISSUE THREAD

**Issue by 2dpdlja496or43iq** [mirkosertic/Bytecoder#886]

**Comment by nbrugger-tgm** [comment]
The core api for `String`, `StringBuilder` and especially `Pattern`/`Matcher` are not fully/at all implemented at the moment.
I am working on it, but I doubt that JEdit can work without methods such as `String.contains()` or `Pattern.match()`. The String+String builder implementation should support the full java20 String API end of next week if i get to it but the Pattern and Matching api require a lot of custom translation so this will take a while.

> Note: I am not an official contributor (yet :P )

**Comment by mirkosertic** [comment]
Bytecoder does not support Swing at the moment. I'll close this ticket for now.
