### ISSUE TITLE
Auto Export static main method

### ISSUE THREAD

**Issue by norzak** [mirkosertic/Bytecoder#90]
Is it possible to automatically export static main method?

**Comment by mirkosertic** [comment]
At the moment, only the WebAssembly backend generates an implicit export named "main" export, the JS backend needs an Export annotation. This should definitely be unified.

However, how would you like the main method be exported if there is no annotation available?

**Comment by norzak** [comment]
Wouldnt searching for the main method in application classes suffice?

**Comment by mirkosertic** [comment]
It would, for sure. But there might be the case that there are multiple main methods available. As the module system makes export names distinct and unique, we need some kind of naming convention. So at the moment i think that there can be only one main method in the whole program and class structure.

So by default, that main method would be exported as "main". Would that be ok?

**Comment by norzak** [comment]
Yes, that would be perfect. In addition, you can first check the META-INF
file for the main class if there is one.

**Comment by mirkosertic** [comment]
The last commit exports the main method also for JS compile target as export name "main" if there is no export annotation available.

**Comment by norzak** [comment]
Sounds great
